////////////////////////////////////////////////////////////////////////
// Class:       MichelWfmReco
// Module Type: producer
// File:        MichelWfmReco_module.cc
//
// This module is used to perform some ID and reconstruction of PMT
// waveforms from stopping/decaying muons (primarily in the Michel 
// trigger sample).
//
// Eventually it may be used to create a new data product related to 
// Michel events, but for now, it does not add to the data file (despite
// being a producer).
//
// Authors: William Foreman, wforeman@uchicago.edu
//
// Generated at Wed Jul 15 13:09:43 2015 by William Foreman using artmod
// from cetpkgsupport v1_08_06.
//
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "art/Framework/Services/Optional/TFileService.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"
#include "art/Framework/Services/Optional/TFileDirectory.h"

//C++ Includes
#include <iostream>
#include <fstream>
#include <vector>
#include <memory>
#include <utility>

//ROOT Includes
#include <TF1.h>
#include <TH1F.h>
#include <TH1I.h>
#include <TH2F.h>
#include <TH3F.h>
#include <TTree.h>

// LArSoft Includes
#include "Utilities/AssociationUtil.h"
#include "RawData/TriggerData.h"
#include "RecoBase/Track.h"
#include "AnalysisBase/Calorimetry.h"
#include "AnalysisBase/ParticleID.h"

//LAriatSoft Includes
#include "RawDataUtilities/TriggerDigitUtility.h"
#include "LArIATRecoAlg/OpHitBuilderAlg.h"
#include "LArIATRecoAlg/TriggerFilterAlg.h"
#include "Utilities/DatabaseUtilityT1034.h"


class MichelWfmReco;

class MichelWfmReco : public art::EDProducer {
public:
  explicit MichelWfmReco(fhicl::ParameterSet const & pset);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  MichelWfmReco(MichelWfmReco const &) = delete;
  MichelWfmReco(MichelWfmReco &&) = delete;
  MichelWfmReco & operator = (MichelWfmReco const &) = delete;
  MichelWfmReco & operator = (MichelWfmReco &&) = delete;

  // Required functions.
  void produce(art::Event & e) override;

  // Selected optional functions.
  void beginJob() override;
  void beginRun(art::Run & r) override;
  void beginSubRun(art::SubRun & sr) override;
  void endJob() override;
  void endRun(art::Run & r) override;
  void endSubRun(art::SubRun & sr) override;
  void reconfigure(fhicl::ParameterSet const & pset) override;
  void respondToCloseInputFile(art::FileBlock const & fb) override;
  void respondToCloseOutputFiles(art::FileBlock const & fb) override;
  void respondToOpenInputFile(art::FileBlock const & fb) override;
  void respondToOpenOutputFiles(art::FileBlock const & fb) override;
  
  // Custom functions
  bool IsPointInFiducialVolume(TVector3);

private:

  // Name of the module producing the triggers
  std::string fTriggerUtility;

  // Tunable parameters from fcl
  bool            bUseTriggerFilter;
  bool            bUseTrackInformation;
  bool            bVerbose;
  std::string     fDAQModule;
  std::string     fTrackModule;
  std::string     fParticleIDModule;
  std::string     fTrackCalModule;
  std::string     fInstanceName;
  double          fTimestampCut;
  short           fGateDelay;
  short           fDtIntegralCut;
  short           fBaselineWindowLength;
  short           fPromptWindowLength;
  short           fFullWindowLength;
  short           fPrePulseBaselineFit;
  double          fFiducialMargin_X;
  double          fFiducialMargin_Y;
  double          fFiducialMargin_Z; 

  // Alg objects
  OpHitBuilderAlg   fOpHitBuilderAlg; 
  OpHitBuilderAlg   fOpHitBuilderAlg_ave1;
  OpHitBuilderAlg   fOpHitBuilderAlg_ave2;
  OpHitBuilderAlg   fOpHitBuilderAlg_aveMIP;
  OpHitBuilderAlg   fOpHitBuilderAlg_aveProton;
  TriggerFilterAlg  fTrigFiltAlg;

  // Variables/vectors
  int                   iEvent;
  bool                  GotETL;
  bool                  flag;
  std::vector<short>    ETL_waveform;
  short                 PostPercentMark;
  int                   NSamples;
  int                   MuTrackIndex;
  TVector3              region_centerpoint;
  double                region_radius;
  std::vector<double>   hit_info;
  std::vector<TVector3> vTrackVertex;
  std::vector<TVector3> vTrackEnd;
  TVector3              MuTrackVertex;
  TVector3              MuTrackEnd;
  int                   HitWaveformBins;

  // Histograms
  TH1I* h_NumOpHits;
  TH2I* h_NumOpHits_vs_NumTracks;
  TH1I* h_NumOpHits_beam;
  TH1I* h_NumOpHits_offbeam;
  TH1F* h_DeltaTime_chargeCut;
  TH1F* h_DeltaTime_stoppingMu;
  TH1F* h_DeltaTime_chargeCut_beam;

  TH1F* h_Amplitude;
  TH1F* h_HitTime;
  TH1F* h_HitAmplitude;
  TH1F* h_Charge100ns;
  TH1F* h_Charge100ns_populationCut;
  TH1F* h_Charge100ns_populationCut_DtCut;
  TH1F* h_Charge100ns_stoppingMu;
  TH1F* h_Charge100ns_region;
  TH1F* h_ChargeFull_populationCut;
  TH1F* h_ChargeFull_populationCut_DtCut;
  TH1F* h_ChargeFull_region;
  TH2F* h_Amplitude_vs_Charge100ns;
  TH1F* h_TrackVertex_x;
  TH1F* h_TrackVertex_y;
  TH1F* h_TrackVertex_z;
  TH1F* h_TrackEnd_x;
  TH1F* h_TrackEnd_y;
  TH1F* h_TrackEnd_z;
  TH2F* h_TrackNode_zx;
  TH2F* h_TrackNode_zy;
  TH2F* h_TrackEnergy_vs_PromptLight;
  TH2I* h_InFiducialVolume;
  TH1F* h_SecondTrackOffset;
  TH1F* h_AverageWaveform1;
  TH1F* h_AverageWaveform2;
  TH1F* h_AverageWaveformMIP;
  TH1F* h_AverageWaveformProton;

  // Storing run information
  int                     RunNumber;
  int                     SubRunNumber;
  int                     EventNumber;

  // Storing optical hit information
  int                     NumHits;
  std::vector<short>      vHitTimes;
  std::vector<double>     vHitAmplitude;
  std::vector<double>     vHitPromptLight;
  std::vector<double>     vHitFullLight;
  std::vector<double>     vPrepulseBaseline;
  std::vector<double>     vPrepulseRMS;
  std::vector<double>     vPrepulseNorm;
  std::vector<double>     vPrepulseTau;
  std::vector<int>        vIsInBGPopulation; 
  std::vector<short>      HitWaveform;
  int                     HitWaveformIndex;
  Double_t                WaveformBaseline;
  Double_t                WaveformBaselineRMS;
  Double_t                Timestamp;
  Int_t                   IsBeamEvent;
  Int_t                   IsCleanBeamWaveform;
  Double_t                DeltaTime;
  Double_t                Amplitude;
  Double_t                Charge_100ns; 
  Double_t                Charge_Full;
  Int_t                   NumTracks;
  std::vector<double>     vTrackVertex_x;
  std::vector<double>     vTrackVertex_y;
  std::vector<double>     vTrackVertex_z;
  std::vector<double>     vTrackEnd_x;
  std::vector<double>     vTrackEnd_y;
  std::vector<double>     vTrackEnd_z;
  std::vector<int>        vIsTrackStopping;
  std::vector<int>        vIsTrackPassing;
  std::vector<int>        vIsTrackContained;
  std::vector<int>        vTrackPID;
  std::vector<double>     vTrackPIDA;
  std::vector<double>     vTrackEnergy;
  std::vector<double>     vTrackLength;
  Int_t                   IsSinglePassingTrack;
  Int_t                   IsSingleStoppingTrack;
  Double_t                StoppingTrackZenithAngle;
  Double_t                PassingTrackZenithAngle;
  Double_t     MuTrackVertex_x;
  Double_t     MuTrackVertex_y;
  Double_t     MuTrackVertex_z;
  Double_t     MuTrackEnd_x;
  Double_t     MuTrackEnd_y;
  Double_t     MuTrackEnd_z;
  Double_t                MuTrackLength;
  Double_t                MuTrackEnergy;
  Int_t                   MuAmplitude;
  Double_t                MuCharge_100ns;
  Double_t                SecondTrackProximity;
  Double_t                SecondTrackLength;
  Double_t                SecondTrackEnergy;
  Int_t                   IsSecondTrackContained;
  
  // TTree info
  TTree* MichelDataTree;

};



MichelWfmReco::MichelWfmReco(fhicl::ParameterSet const & pset)
: fOpHitBuilderAlg(pset), fOpHitBuilderAlg_ave1(pset), fOpHitBuilderAlg_ave2(pset), fOpHitBuilderAlg_aveMIP(pset), fOpHitBuilderAlg_aveProton(pset), fTrigFiltAlg(pset)
{

  // Configures the ROOT histograms
  this->reconfigure(pset);
  
  // Produces the LArSoft object to be outputted
  // (none for now!) 
 
  // TO DO: make this a fcl parameter 
  region_centerpoint.SetXYZ(23.5,0.,45.);
  region_radius = 10.;

  fOpHitBuilderAlg_ave1.AddHitToAverageWaveform = 1;  
  fOpHitBuilderAlg_ave2.AddHitToAverageWaveform = 1;  
  fOpHitBuilderAlg_aveMIP.AddHitToAverageWaveform = 1;  
  fOpHitBuilderAlg_aveProton.AddHitToAverageWaveform = 1;  

  HitWaveformBins = (int)fPrePulseBaselineFit+(int)fFullWindowLength;
  HitWaveform.reserve(HitWaveformBins);

}


void MichelWfmReco::produce(art::Event & e)
{
  iEvent++;

  NumHits = -9;
  RunNumber         = -9;
  SubRunNumber      = -9;
  EventNumber       = -9;
  Timestamp         = -9.; 
  IsCleanBeamWaveform = -9;
  IsBeamEvent       = -9;
  NumTracks         = -9;
  IsSingleStoppingTrack   = 0;
  IsSinglePassingTrack    = 0;
  StoppingTrackZenithAngle = -1;
  PassingTrackZenithAngle   = -1;
  vTrackVertex_x.clear();
  vTrackVertex_y.clear();
  vTrackVertex_z.clear();
  vTrackEnd_x.clear();
  vTrackEnd_y.clear();
  vTrackEnd_z.clear();
  vTrackEnergy.clear();
  vTrackLength.clear();
  vTrackPID.clear();
  vTrackPIDA.clear();
  vIsTrackStopping.clear();
  vIsTrackPassing.clear();
  vIsTrackContained.clear();
  MuTrackVertex_x   = -99.;
  MuTrackVertex_y  = -99.;
  MuTrackVertex_z   = -99.;
  MuTrackEnd_x      = -99.;
  MuTrackEnd_y      = -99.;
  MuTrackEnd_z      = -99.;
  MuTrackLength     = -99.;
  MuTrackEnergy     = -99.;
  MuAmplitude       = -99;
  MuCharge_100ns    = -999.;
  DeltaTime         = -99.;
  Amplitude         = -99.;
  Charge_100ns      = -9999.;
  Charge_Full       = -99999.;
  WaveformBaseline  = -99.;
  WaveformBaselineRMS = -9.;
  SecondTrackLength = -9.;
  SecondTrackEnergy = -9.;
  SecondTrackProximity = -9.;
  IsSecondTrackContained = -9;
  vHitTimes.clear();
  vHitAmplitude.clear();
  vHitPromptLight.clear();
  vHitFullLight.clear();
  vIsInBGPopulation.clear();
  vPrepulseBaseline.clear();
  vPrepulseRMS.clear();
  vPrepulseNorm.clear();
  vPrepulseTau.clear();
  vTrackVertex.clear();
  vTrackEnd.clear();

  for(unsigned int i=0; i<HitWaveform.size(); i++) HitWaveform[i] = 0;
  HitWaveformIndex = -9;

  // Get run and event number
  RunNumber     = (int)e.run();
  SubRunNumber  = (int)e.subRun();
  EventNumber   = (int)e.event();
  
  
  // Filter for the MICHEL trigger pattern (note that for some runs, particularly for 
  // those with the optimized Michel trigger setup, unfortunately the trigger inputs 
  // were not being saved and thus the filter won't work).
  /*
  bool isMichel = 1; 
  if (bUseTriggerFilter){
    std::string myFilter = "+MICHEL";
    isMichel = fTrigFiltAlg.doesTriggerPassFilter( thisTrigger, myFilter ); 
  } else {
    isMichel = 1;
  }
  if ( !isMichel ) return;
  */

  // Get the OpDetPulses; skip event if empty
  art::Handle< std::vector< raw::OpDetPulse >> WaveformHandle;
  e.getByLabel(fDAQModule,fInstanceName,WaveformHandle);
  if( (int)WaveformHandle->size() == 0 ) {
    if(bVerbose) std::cout<<"No optical detector data found -- skipping the event\n";
    return;
  } else {
    // If not empty, store ETL waveform
    GotETL = false;
    for( int ipulse = 0; ipulse < (int)WaveformHandle->size(); ipulse++){
      art::Ptr< raw::OpDetPulse > ThePulsePtr(WaveformHandle,ipulse);
      raw::OpDetPulse ThePulse = *ThePulsePtr;
      if( ThePulse.OpChannel() == 1) {
        ETL_waveform = ThePulse.Waveform();
        NSamples = ETL_waveform.size();
        Timestamp = (double(ThePulse.PMTFrame())*8.)/1.0e09;
        PostPercentMark = short(ThePulse.FirstSample()); 
        GotETL = true;
        
        if(bVerbose){
          std::cout<<"ETL pulse recorded."<<std::endl;
          std::cout<<"  Nsamples = "<<NSamples<<std::endl;
          std::cout<<"  PMTFrame = "<<ThePulse.PMTFrame()<<std::endl;
          std::cout<<"  FirstSample = "<<ThePulse.FirstSample()<<std::endl;
          std::cout<<"  Timestamp = "<<Timestamp<<" sec"<<std::endl;
        }

        // Is clean beam waveform? (for testing out function)
        IsCleanBeamWaveform = fOpHitBuilderAlg.IsCleanBeamWaveform(ThePulse);
      }
    }
  }
  // If we somehow didn't get the ETL, skip the event
  if( !GotETL ) return;

  // Classify as beam or non-beam event (allow 0.1s buffer around cutoff just to be safe)
  if ( (Timestamp >= 0)&&(Timestamp < fTimestampCut-0.1)){ IsBeamEvent = 1;}
  else if (Timestamp >= fTimestampCut+0.1) { IsBeamEvent = 0;}

  //  Get waveform baseline/RMS
  std::vector<double> tmp = fOpHitBuilderAlg.GetBaselineAndRMS(ETL_waveform,0,fBaselineWindowLength);
  WaveformBaseline = tmp[0];
  WaveformBaselineRMS = tmp[1];
  if(bVerbose) std::cout<<"Baseline: "<<WaveformBaseline<<"  RMS: "<<WaveformBaselineRMS<<"\n";
  
  // Perform hit-finding/filtering
  vHitTimes = fOpHitBuilderAlg.GetHits(ETL_waveform);
  NumHits = vHitTimes.size();
  if(bVerbose) {
    std::cout << "Performing optical hitfinding...\n"; 
    std::cout << "We found "<<NumHits<<" hits\n";
  }
  
  // If exactly 2 hits, measure their time difference
  if(NumHits == 2){
    DeltaTime = double(vHitTimes[1] - vHitTimes[0]);
    if(bVerbose) std::cout<<"    DeltaT = "<<DeltaTime<<std::endl;
  }
  
  // For each hit, do all the needed reconstruction in single function call
  for (int i=0; i<NumHits; i++){
    if(bVerbose) std::cout<<"   "<<i<<"    t = "<<vHitTimes[i]<<"\n";
    hit_info = fOpHitBuilderAlg.GetHitInfo(ETL_waveform, vHitTimes[i]);
    
    h_HitTime       ->Fill(vHitTimes[i]);
    vHitAmplitude.push_back(hit_info[0]);
    h_HitAmplitude  ->Fill(vHitAmplitude[i]);
    vHitPromptLight.push_back(hit_info[1]);
    vHitFullLight.push_back(hit_info[2]);
    vPrepulseBaseline.push_back(fOpHitBuilderAlg.prepulse_baseline);
    vPrepulseRMS.push_back(fOpHitBuilderAlg.prepulse_rms);
    vPrepulseNorm.push_back(fOpHitBuilderAlg.fit_norm);
    vPrepulseTau.push_back(fOpHitBuilderAlg.fit_tau); 
    
    // Line in amplitude (mV,x) vs. charge (ADC,y) space to cut out background. 
    TF1 f_PopulationCut("f_PopulationCut","48.04*x + 404.9",0.,150.);
    if( vHitPromptLight[i] > f_PopulationCut.Eval(vHitAmplitude[i])){ 
      vIsInBGPopulation.push_back(0);
    } else {
      vIsInBGPopulation.push_back(1); 
    }
 
  }
  

  if(bUseTrackInformation){ 
    
    // Get the tracks and their associated energy
    art::Handle< std::vector< recob::Track >> TrackHandle;
    e.getByLabel(fTrackModule,TrackHandle);
  
    // Fill tracklist... (not used right now)
    //std::vector< art::Ptr< recob::Track >> tracklist; 
    //if (e.getByLabel(fTrackModule,TrackHandle))
    //   {art::fill_ptr_vector(tracklist, trackListHandle);}

    NumTracks = (int)TrackHandle->size();

    if(bVerbose) std::cout<<"Number of tracks: "<<NumTracks<<"\n";
  
    // === Association between Calorimetry objects and Tracks ===
    art::FindManyP<anab::Calorimetry> fmcal(TrackHandle, e, fTrackCalModule);
    // === Association between PID objects and Tracks ===
    art::FindManyP<anab::ParticleID>  fmpid(TrackHandle, e, fParticleIDModule);
    
    // Loop through the track list and store their properties
    for( int track_index = 0; track_index < NumTracks; track_index++){
  
      // Get the recob::Track object and record its endpoint/vertex
      art::Ptr< recob::Track > TheTrackPtr(TrackHandle,track_index);
      recob::Track TheTrack = *TheTrackPtr;
      vTrackEnd.push_back(TheTrack.End());
      vTrackVertex.push_back(TheTrack.Vertex());
      vTrackLength.push_back(TheTrack.Length());
    
      vTrackVertex_x.push_back(TheTrack.Vertex().X());
      vTrackVertex_y.push_back(TheTrack.Vertex().Y());
      vTrackVertex_z.push_back(TheTrack.Vertex().Z());
      vTrackEnd_x.push_back(TheTrack.End().X()); 
      vTrackEnd_y.push_back(TheTrack.End().Y()); 
      vTrackEnd_z.push_back(TheTrack.End().Z()); 

      bool endIsInFid = IsPointInFiducialVolume(TheTrack.End());
      bool vertexIsInFid = IsPointInFiducialVolume(TheTrack.Vertex());
      int temp_flag = ((!endIsInFid && vertexIsInFid)||(endIsInFid && !vertexIsInFid));
      
      // Is track stopping, passing, or contained?
      vIsTrackStopping.push_back( temp_flag);
      vIsTrackPassing.push_back(   !endIsInFid && !vertexIsInFid);
      vIsTrackContained.push_back( endIsInFid && vertexIsInFid );
      
      /*
      if(bVerbose){
        std::cout<<"  track "<<track_index<<" vertex("
        << TheTrack.Vertex().X() <<"," 
        << TheTrack.Vertex().Y() << "," 
        << TheTrack.Vertex().Z() << ")->InFiducial()="
        << vertexIsInFid 
        << "   end("
        << TheTrack.End().X() <<"," 
        << TheTrack.End().Y() << "," 
        << TheTrack.End().Z() << ")->InFiducial()="
        << endIsInFid << std::endl;
      }
      */

      h_InFiducialVolume->Fill(vertexIsInFid,endIsInFid);

      h_TrackNode_zx->Fill(TheTrack.Vertex().Z(),TheTrack.Vertex().X());
      h_TrackNode_zx->Fill((float)TheTrack.End().Z(),(float)TheTrack.End().X());
      h_TrackNode_zy->Fill((float)TheTrack.Vertex().Z(),(float)TheTrack.Vertex().Y());
      h_TrackNode_zy->Fill((float)TheTrack.End().Z(),(float)TheTrack.End().Y());
      

      // ################################################### 
      // ### Looping over calorimetry info for the track ###
      // ################################################### 
      if( fmcal.isValid() ){
        std::vector<art::Ptr<anab::Calorimetry> > calos = fmcal.at(track_index);
        // calos[0] is from induction plane
        // calos[1] is from collection plane
        vTrackEnergy.push_back(calos[1]->KineticEnergy());
        //if(bVerbose) std::cout<<"  KE = "<<calos[1]->KineticEnergy()<<std::endl; 
      } else {
        //if(bVerbose) std::cout<<"  KE = undefined"<<std::endl;
        vTrackEnergy.push_back(-99.);
      }
   
      // ################################################## 
      // ### Looping over PID information for the track ###
      // ################################################## 
      if (fmpid.isValid()){
        std::vector<art::Ptr<anab::ParticleID> > pids = fmpid.at(track_index);
        // pids[0] = induction
        // pids[1] = collection
        if (!pids[1]->PlaneID().isValid) {
        if(bVerbose) std::cout<<"  pid["<<track_index<<"]: undefined\n";
          vTrackPID.push_back(-99); 
          vTrackPIDA.push_back(-99);
          continue;
        }
        vTrackPID.push_back(pids[1]->Pdg());
        vTrackPIDA.push_back(pids[1]->PIDA());
        if(bVerbose) std::cout<<"  pid["<<track_index<<"]: "<<pids[1]->Pdg()<<"\n";
      } else {
        if(bVerbose) std::cout<<"  pid["<<track_index<<"]: undefined\n";
        vTrackPID.push_back(-99);
        vTrackPIDA.push_back(-99);
      }

    
    
    } // End loop over tracks  

    // --------------------------------------
    // Higher-level track filtering:
    
    // Require no more than two tracks in the event:
    if( NumTracks <= 2 ) {
      
      flag = false;
  
      // Cycle through tracks
      for( int i=0; i<NumTracks; i++){
          
        // Since we don't want to blindly trust that the endpoint and 
        // vertex have been assigned correctly, let's say whichever 
        // has a higher Y-value is the vertex (pretty reasonable 
        // assumption for cosmic muons).
        TVector3 vertex;
        TVector3 end;
        if( vTrackVertex[i].Y() > vTrackEnd[i].Y()  ) { 
          vertex  = vTrackVertex[i]; 
          end     = vTrackEnd[i];
        } else {
          vertex  = vTrackEnd[i];
          end     = vTrackVertex[i];
        }
      
        // Fill histograms
        h_TrackEnd_x->Fill(end.X());
        h_TrackEnd_y->Fill((float)end.Y());
        h_TrackEnd_z->Fill((float)end.Z());
        h_TrackVertex_x->Fill((float)vertex.X());
        h_TrackVertex_y->Fill((float)vertex.Y());
        h_TrackVertex_z->Fill((float)vertex.Z());

         
        // If there's a single stopping track, fill Mu variables
        if( !flag && vIsTrackStopping[i] ) {
          
          // If there was already a stopping track, this disqualifies 
          // the event.
          if( IsSingleStoppingTrack ){
            std::cout<<"More than one stopper!\n";
            IsSingleStoppingTrack = 0;
            flag = true;
            MuTrackVertex_x   = -99.;
            MuTrackVertex_y   = -99.;
            MuTrackVertex_z   = -99.;
            MuTrackEnd_x      = -99.;
            MuTrackEnd_y      = -99.;
            MuTrackEnd_z      = -99.;
            MuTrackLength     = -9.;
            MuTrackEnergy     = -9.;
            StoppingTrackZenithAngle = -9.;
          } else { 
            std::cout<<"Found a stopper\n";
            MuTrackIndex = i;
            IsSingleStoppingTrack = 1;
            MuTrackVertex   = vertex;
            MuTrackEnd      = end;
            MuTrackVertex_x   = MuTrackVertex.X();
            MuTrackVertex_y   = MuTrackVertex.Y();
            MuTrackVertex_z   = MuTrackVertex.Z();
            MuTrackEnd_x      = MuTrackEnd.X();
            MuTrackEnd_y      = MuTrackEnd.Y();
            MuTrackEnd_z      = MuTrackEnd.Z();
            MuTrackLength   = vTrackLength[i];
            MuTrackEnergy   = vTrackEnergy[i];
            TVector3 vert(0.,1.,0.);
            TVector3 tmp = (vertex-end);
            StoppingTrackZenithAngle = tmp.Angle(vert);
            std::cout<<"zenith angle: "<<StoppingTrackZenithAngle<<std::endl;
          }
        
        }
      } 
    }
 
    // Look for single passing tracks
    if( (NumTracks == 1)&&( vIsTrackPassing[0])) {
      IsSinglePassingTrack = 1;
      MuTrackIndex = 0;
      MuTrackVertex   = vTrackVertex[0];
      MuTrackEnd      = vTrackEnd[0];
      MuTrackVertex_x   = MuTrackVertex.X();
      MuTrackVertex_y   = MuTrackVertex.Y();
      MuTrackVertex_z   = MuTrackVertex.Z();
      MuTrackEnd_x      = MuTrackEnd.X();
      MuTrackEnd_y      = MuTrackEnd.Y();
      MuTrackEnd_z      = MuTrackEnd.Z();
      MuTrackLength   = vTrackLength[0];
      MuTrackEnergy   = vTrackEnergy[0];

      TVector3 vert(0.,1.,0.);
      TVector3 tmp = (MuTrackVertex-MuTrackEnd);
      PassingTrackZenithAngle = tmp.Angle(vert);  
    }
  
    // If there was a stopping "muon" and a second track, check
    // to see if either of its endpoints is close to muon endpoint.
    if( IsSingleStoppingTrack && NumTracks == 2 ) {
      for( int i=0; i<NumTracks; i++){
        if( i != MuTrackIndex ){
          SecondTrackProximity = std::min( 
            (vTrackVertex[i] - MuTrackEnd).Mag(),
            (vTrackEnd[i]   - MuTrackEnd).Mag());
          h_SecondTrackOffset->Fill(SecondTrackProximity);
          SecondTrackLength = vTrackLength[i];
          SecondTrackEnergy = vTrackEnergy[i];
          IsSecondTrackContained = vIsTrackContained[i];
        }
      }  
    }

    // If there was 1 stopping or 1 passing track, get light info for the "muon"
    if( (IsSingleStoppingTrack||IsSinglePassingTrack) && (NumHits > 0)&&(NumHits <= 2) ) {
      MuAmplitude = vHitAmplitude[0];
      MuCharge_100ns = vHitPromptLight[0];
    }

  } //endif bUseTrackInformation

  if( (NumTracks==1)&&(NumHits==1)&&(vTrackEnergy[0]>0.)&&(vHitAmplitude[0]<190.)){
    h_TrackEnergy_vs_PromptLight->Fill(vTrackEnergy[0],vHitPromptLight[0]);
  }
    

  // Fill NumOpHits histo (beam vs. offbeam)
  h_NumOpHits ->Fill(NumHits);
  h_NumOpHits_vs_NumTracks->Fill(NumHits,NumTracks);
  if(IsBeamEvent)   h_NumOpHits_beam    ->Fill(NumHits);
  if(!IsBeamEvent)  h_NumOpHits_offbeam ->Fill(NumHits);
  
        
  // Only proceed to save charge/amplitude variables if 
  // the pulses are far enough apart such that the tail of the
  // first does not contiminate the second (fcl setting, default 0)
  // Note: Requiring DeltaTime > 0 ensures there were only 2 hits. 

  if(NumHits==2){      
    // Integral/amplitude of Michel pulse
    Amplitude     = vHitAmplitude[1];
    Charge_100ns  = vHitPromptLight[1];
    Charge_Full   = vHitFullLight[1];
    if(bVerbose) std::cout<<"    Amplitude = "<<Amplitude<<std::endl;
    if(bVerbose) std::cout<<"    Charge prompt = "<<Charge_100ns<<std::endl;
    if(bVerbose) std::cout<<"    Charge full = "<<Charge_Full<<" \n";

  }
  
  if( (NumHits>0)&&(NumHits<=2) ){
    // Save the waveform
    HitWaveformIndex = NumHits-1;
    for(int i=0; i<HitWaveformBins; i++){
      HitWaveform[i] = ETL_waveform[vHitTimes[HitWaveformIndex]-fPrePulseBaselineFit+i]; 
    }
  }
  
  
  // Michel event quality control:
  // Require 2 hits (one before PostPercent, one within 1% of PostPercent) 
  if( (NumHits == 2) && (vHitTimes[0] < vHitTimes[1]-fGateDelay) && ( abs(vHitTimes[1]-PostPercentMark) <= 0.01*NSamples) && (!IsBeamEvent)){
    
    if(bVerbose) std::cout << "--> passes Michel trigger cut (off-beam) \n";

    h_Amplitude->Fill(Amplitude);
    h_Charge100ns->Fill(Charge_100ns); 
    h_Amplitude_vs_Charge100ns->Fill(Amplitude,Charge_100ns);
    
    if( Charge_100ns > 1800. ) {
      h_DeltaTime_chargeCut ->Fill(DeltaTime);
    }

    if( !vIsInBGPopulation[1] ) {
      h_Charge100ns_populationCut->Fill(Charge_100ns);
      h_ChargeFull_populationCut->Fill(Charge_Full);
      
      if( DeltaTime > 3000. ){
        h_Charge100ns_populationCut_DtCut->Fill(Charge_100ns);
        h_ChargeFull_populationCut_DtCut->Fill(Charge_Full);
      } 
    }
  
    if( IsSingleStoppingTrack ) {
      h_Charge100ns_stoppingMu->Fill(Charge_100ns);
      h_DeltaTime_stoppingMu->Fill(DeltaTime);
      if( (MuTrackEnd-region_centerpoint).Mag() <= region_radius) {
        h_Charge100ns_region->Fill(Charge_100ns);
        h_ChargeFull_region->Fill(Charge_Full);
      }
    }
     
    // Make average waveform of the "good" Michel events
    if( (DeltaTime > 3000.)&&(!vIsInBGPopulation[1])) fOpHitBuilderAlg_ave1.GetHitInfo(ETL_waveform,vHitTimes[1]);
    
    // Make average waveform of the BG events
    if( (DeltaTime > 3000.)&&(vIsInBGPopulation[1])) fOpHitBuilderAlg_ave2.GetHitInfo(ETL_waveform,vHitTimes[1]);

    // Make average waveform of muons
    if( (NumHits<=2)&&(NumTracks==1)&&( abs(vTrackPID[0])==13)
      &&( abs(vHitTimes[0]-PostPercentMark) <= 0.02*NSamples)) {
      fOpHitBuilderAlg_aveMIP.GetHitInfo(ETL_waveform,vHitTimes[0]);
    }
    
    // Make average waveform of beam protons
    if( (NumHits<=2)&&(NumTracks==1)&&(abs(vTrackPID[0])==2212)&&(IsBeamEvent)
      &&( abs(vHitTimes[0]-PostPercentMark) <= 0.02*NSamples)) {
      fOpHitBuilderAlg_aveProton.GetHitInfo(ETL_waveform,vHitTimes[0]);
    }


    
  

  } // end quality cut condition (off-beam)


  // Also look at DeltaTime of beam events where there was a delayed optical hit
  if( (NumHits == 2) && ( abs(vHitTimes[0]-PostPercentMark) <= 0.01*NSamples) && (IsBeamEvent) ){
    if( Charge_100ns > 1800 ) h_DeltaTime_chargeCut_beam->Fill(DeltaTime);
  }

  // Done with this event so fill the tree
  MichelDataTree->Fill();
  
  // Add space in printout to separate events (for easier debugging)
  if(bVerbose) std::cout<<std::endl;
}


void MichelWfmReco::beginJob()
{
  // Opens up the file service to read information from the ROOT file input
  art::ServiceHandle<art::TFileService> tfs;

  MichelDataTree  = tfs->make<TTree>("MichelDataTree","MichelDataTree");
 
  // Event identifying information 
  MichelDataTree  ->Branch("RunNumber",&RunNumber,"RunNumber/I");
  MichelDataTree  ->Branch("SubRunNumber",&SubRunNumber,"SubRunNumber/I");
  MichelDataTree  ->Branch("EventNumber",&EventNumber,"EventNumber/I");
  MichelDataTree  ->Branch("Timestamp",&Timestamp,"Timestamp/D");
  MichelDataTree  ->Branch("IsBeamEvent",&IsBeamEvent,"IsBeamEvent/I");

  // Waveform hit information
  MichelDataTree ->Branch("HitWaveform",&HitWaveform);
  MichelDataTree ->Branch("HitWaveformIndex",&HitWaveformIndex,"HitWaveformIndex/I");
  MichelDataTree ->Branch("WaveformBaseline",&WaveformBaseline,"WaveformBaseline/D");
  MichelDataTree ->Branch("WaveformBaselineRMS",&WaveformBaselineRMS,"WaveformBaselineRMS/D");
  MichelDataTree ->Branch("NumHits",&NumHits,"NumHits/I");
  MichelDataTree ->Branch("HitTimes",&vHitTimes);
  MichelDataTree ->Branch("HitAmplitude",&vHitAmplitude);
  MichelDataTree ->Branch("HitPromptLight",&vHitPromptLight);
  MichelDataTree ->Branch("HitFullLight",&vHitFullLight); 
  MichelDataTree ->Branch("PrepulseBaseline",&vPrepulseBaseline);
  MichelDataTree ->Branch("PrepulseRMS",&vPrepulseRMS);
  MichelDataTree ->Branch("PrepulseNorm",&vPrepulseNorm);
  MichelDataTree ->Branch("PrepulseTau",&vPrepulseTau);
  MichelDataTree ->Branch("IsInBGPopulation",&vIsInBGPopulation);
  MichelDataTree ->Branch("IsCleanBeamWaveform",&IsCleanBeamWaveform,"IsCleanBeamWaveform/I");
  
  // Michel-candidate information
  MichelDataTree->Branch("DeltaTime",&DeltaTime,"DeltaTime/D");
  MichelDataTree->Branch("Amplitude",&Amplitude,"Amplitude/D");
  MichelDataTree->Branch("Charge_100ns",&Charge_100ns,"Charge_100ns/D");
  MichelDataTree->Branch("Charge_Full",&Charge_Full,"Charge_Full/D");
  
  // Track information
  MichelDataTree->Branch("NumTracks",&NumTracks,"NumTracks/I");
  MichelDataTree->Branch("TrackVertex_x",&vTrackVertex_x);
  MichelDataTree->Branch("TrackVertex_y",&vTrackVertex_y);
  MichelDataTree->Branch("TrackVertex_z",&vTrackVertex_z);
  MichelDataTree->Branch("TrackEnd_x",&vTrackEnd_x);
  MichelDataTree->Branch("TrackEnd_y",&vTrackEnd_y);
  MichelDataTree->Branch("TrackEnd_z",&vTrackEnd_z);
  MichelDataTree->Branch("IsTrackStopping",&vIsTrackStopping);
  MichelDataTree->Branch("IsTrackPassing",&vIsTrackPassing);
  MichelDataTree->Branch("IsTrackContained",&vIsTrackContained);
  MichelDataTree->Branch("TrackPID",&vTrackPID);
  MichelDataTree->Branch("TrackPIDA",&vTrackPIDA);
  MichelDataTree->Branch("TrackLength",&vTrackLength);
  MichelDataTree->Branch("TrackEnergy",&vTrackEnergy);
  MichelDataTree->Branch("IsSinglePassingTrack",&IsSinglePassingTrack,"IsSinglePassingTrack/I");
  MichelDataTree->Branch("IsSingleStoppingTrack",&IsSingleStoppingTrack,"IsStoppingTrack/I");
  MichelDataTree->Branch("StoppingTrackZenithAngle",&StoppingTrackZenithAngle,"StoppingTrackZenithAngle/D");
  MichelDataTree->Branch("PassingTrackZenithAngle",&PassingTrackZenithAngle,"PassingTrackZenithAngle/D");
  MichelDataTree->Branch("MuTrackVertex_x",&MuTrackVertex_x,"MuTrackVertex_x/D");
  MichelDataTree->Branch("MuTrackVertex_y",&MuTrackVertex_y,"MuTrackVertex_y/D");
  MichelDataTree->Branch("MuTrackVertex_z",&MuTrackVertex_z,"MuTrackVertex_z/D");
  MichelDataTree->Branch("MuTrackEnd_x",&MuTrackEnd_x,"MuTrackEnd_x/D");
  MichelDataTree->Branch("MuTrackEnd_y",&MuTrackEnd_y,"MuTrackEnd_y/D");
  MichelDataTree->Branch("MuTrackEnd_z",&MuTrackEnd_z,"MuTrackEnd_z/D");
  MichelDataTree->Branch("MuTrackLength",&MuTrackLength,"MuTrackLength/D");
  MichelDataTree->Branch("MuTrackEnergy",&MuTrackEnergy,"MuTrackEnergy/D");
  MichelDataTree->Branch("SecondTrackProximity",&SecondTrackProximity,"SecondTrackProximity/D"); 
  MichelDataTree->Branch("SecondTrackLength",&SecondTrackLength,"SecondTrackLength/D"); 
  MichelDataTree->Branch("SecondTrackEnergy",&SecondTrackEnergy,"SecondTrackEnergy/D"); 
  MichelDataTree->Branch("IsSecondTrackContained",&IsSecondTrackContained,"IsSecondTrackContained/I"); 
 
  // Histograms 
  h_NumOpHits = tfs->make<TH1I>("OpHitsPerEvent", "Optical hits per event", 10, 0, 10);
  h_NumOpHits           ->GetXaxis()->SetTitle("Num hits");
  h_NumOpHits           ->GetYaxis()->SetTitle("Counts");
  h_NumOpHits_beam      = tfs->make<TH1I>("OpHitsPerEvent_beam", "Optical hits per event (beam)",  10, 0, 10);
  h_NumOpHits_beam      ->GetXaxis()->SetTitle("Num hits");
  h_NumOpHits_beam      ->GetYaxis()->SetTitle("Counts");
  h_NumOpHits_offbeam   = tfs->make<TH1I>("OpHitsPerEvent_offbeam", "Optical hits per event (off-beam)", 10, 0, 10);
  h_NumOpHits_offbeam   ->GetXaxis()->SetTitle("Num hits");
  h_NumOpHits_offbeam   ->GetYaxis()->SetTitle("Counts");
  h_NumOpHits_vs_NumTracks = tfs->make<TH2I>("NumOpHits_vs_NumTracks", "Optical hits vs. number of tracks in event", 10, 0,10, 50,0,50);
  h_NumOpHits_vs_NumTracks ->GetXaxis()->SetTitle("Num optical hits");
  h_NumOpHits_vs_NumTracks ->GetYaxis()->SetTitle("Num tracks");
  h_NumOpHits_vs_NumTracks ->SetOption("colz");

  h_DeltaTime_chargeCut = tfs->make<TH1F>("DeltaTime_chargeCut", "#Delta t (prompt integral > 1800ADC)", 700,0., 7000.);
  h_DeltaTime_chargeCut ->GetXaxis()->SetTitle("ns");
  h_DeltaTime_chargeCut ->GetYaxis()->SetTitle("Counts");
  
  h_DeltaTime_stoppingMu = tfs->make<TH1F>("DeltaTime_stoppingMu", "#Delta t (1 stopping track, prompt integral > 1800ADC)", 700,0., 7000.);
  h_DeltaTime_stoppingMu ->GetXaxis()->SetTitle("ns");
  h_DeltaTime_stoppingMu ->GetYaxis()->SetTitle("Counts");

  h_DeltaTime_chargeCut_beam = tfs->make<TH1F>("DeltaTime_chargeCut_beam","#Delta t (prompt integral > 1800ADC) for Michel-like beam event",700,0.,7000.);
  h_DeltaTime_chargeCut_beam    ->GetXaxis()->SetTitle("ns");
  h_DeltaTime_chargeCut_beam    ->GetYaxis()->SetTitle("Counts");

  h_HitTime                 = tfs->make<TH1F>("HitTime", "Hit time in single-hit events",1000,0.,30000.);
  h_HitAmplitude           = tfs->make<TH1F>("HitAmplitude", "Amplitude of found hit in single-hit events", 300,   0., 300.);
  h_HitAmplitude           ->GetXaxis()->SetTitle("Optical hit amplitude [mV]");
  h_HitAmplitude           ->GetYaxis()->SetTitle("Counts");
  h_Amplitude           = tfs->make<TH1F>("Amplitude", "Amplitude", 500,   0., 100.);
  h_Amplitude           ->GetXaxis()->SetTitle("Amplitude of Michel PMT pulse [mV]");
  h_Amplitude           ->GetYaxis()->SetTitle("Counts");
  
  h_Charge100ns          = tfs->make<TH1F>("Charge100ns", "Prompt light integral (100ns)",  480,  0., 12000.);
  h_Charge100ns          ->GetXaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Charge100ns          ->GetYaxis()->SetTitle("Counts");

  h_Charge100ns_populationCut          = tfs->make<TH1F>("Charge100ns_populationCut", "Prompt light integral (100ns), BG population cut",  480,  0., 12000.);
  h_Charge100ns_populationCut          ->GetXaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Charge100ns_populationCut          ->GetYaxis()->SetTitle("Counts");
 
  h_Charge100ns_populationCut_DtCut    = tfs->make<TH1F>("Charge100ns_populationCut_DtCut", "Prompt light integral (100ns), BG population cut, #Delta t > 3us",  480,  0., 12000.);
  h_Charge100ns_populationCut_DtCut    ->GetXaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Charge100ns_populationCut_DtCut    ->GetYaxis()->SetTitle("Counts");
  
  h_Charge100ns_stoppingMu = tfs->make<TH1F>("Charge100ns_stoppingMu","Prompt light integral (100ns) in events with 1 stopping track",480,0.,12000.);
  h_Charge100ns_stoppingMu ->GetXaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Charge100ns_stoppingMu ->GetYaxis()->SetTitle("Counts");

  h_Charge100ns_region    = tfs->make<TH1F>("Charge100ns_region","Prompt light integral (100ns), limited region",480,0.,12000.);
  h_Charge100ns_region    ->GetXaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Charge100ns_region    ->GetYaxis()->SetTitle("Counts");
  
  h_ChargeFull_populationCut          = tfs->make<TH1F>("ChargeFull_populationCut", "Full light integral (7us), BG population cut",  600,  0., 30000.);
  h_ChargeFull_populationCut          ->GetXaxis()->SetTitle("Integrated light, 7us [ADC]");
  h_ChargeFull_populationCut          ->GetYaxis()->SetTitle("Counts");
  
  h_ChargeFull_populationCut_DtCut    = tfs->make<TH1F>("ChargeFull_populationCut_DtCut", "Full light integral (7us), BG population cut, #Delta t > 3us",  600,  0., 30000.);
  h_ChargeFull_populationCut_DtCut    ->GetXaxis()->SetTitle("Integrated light, 7us [ADC]");
  h_ChargeFull_populationCut_DtCut    ->GetYaxis()->SetTitle("Counts");
  
  h_ChargeFull_region    = tfs->make<TH1F>("ChargeFull_region","Full light integral (7us), limited region",600,0.,30000.);
  h_ChargeFull_region    ->GetXaxis()->SetTitle("Integrated light, 7us [ADC]");
  h_ChargeFull_region    ->GetYaxis()->SetTitle("Counts");

  h_Amplitude_vs_Charge100ns = tfs->make<TH2F>("Amplitude_vs_Charge100ns","Pulse amplitude vs. prompt charge (100ns);mV;ADC",200,0.,100.,200,0.,12000.);
  h_Amplitude_vs_Charge100ns ->GetXaxis()->SetTitle("Amplitude of Michel-candidate PMT pulse [mV]");
  h_Amplitude_vs_Charge100ns ->GetYaxis()->SetTitle("Integrated prompt light, 100ns [ADC]");
  h_Amplitude_vs_Charge100ns ->SetOption("colz");
  h_TrackEnergy_vs_PromptLight = tfs->make<TH2F>("TrackEnergy_vs_PromptLight",";Reconstructed track energy [MeV];Prompt light [ADC]",100,0.,150.,100,0.,3000);
  h_TrackEnergy_vs_PromptLight->SetOption("colz");

  h_TrackNode_zx          = tfs->make<TH2F>("TrackNode_zx","TrackNode_zx",180,0.,90.,94,0.,47.);
  h_TrackNode_zx          ->GetXaxis()->SetTitle("z [cm]");
  h_TrackNode_zx          ->GetYaxis()->SetTitle("x [cm]");
  h_TrackNode_zx          ->SetMarkerStyle(7);
  h_TrackNode_zx          ->SetOption("colz");

  h_TrackNode_zy          = tfs->make<TH2F>("TrackNode_zy","TrackNode_zy",180,0.,90.,80,-20.,20.);
  h_TrackNode_zy          ->GetXaxis()->SetTitle("z [cm]");
  h_TrackNode_zy          ->GetYaxis()->SetTitle("y [cm]");
  h_TrackNode_zy          ->SetMarkerStyle(7);
  h_TrackNode_zy          ->SetOption("colz");

  h_TrackEnd_x            = tfs->make<TH1F>("TrackEnd_x","TrackEnd_x",100,-10.,60.);
  h_TrackEnd_y            = tfs->make<TH1F>("TrackEnd_y","TrackEnd_y",100,-25.,25.);
  h_TrackEnd_z            = tfs->make<TH1F>("TrackEnd_z","TrackEnd_z",100,-10.,100.);
  h_TrackVertex_x         = tfs->make<TH1F>("TrackVertex_x","TrackVertex_x",100,-10.,60.);
  h_TrackVertex_y         = tfs->make<TH1F>("TrackVertex_y","TrackVertex_y",100,-25.,25.);
  h_TrackVertex_z         = tfs->make<TH1F>("TrackVertex_z","TrackVertex_z",100,-10.,100.);
  
  h_InFiducialVolume      = tfs->make<TH2I>("InFiducialVolume",";Vertex in fiducial volume;End in fiducial volume",2,0.,2.,2,0.,2.);
  h_InFiducialVolume      ->SetOption("colz");
  
  h_SecondTrackOffset     = tfs->make<TH1F>("SecondTrackOffset","Primary / secondary track endpoint offset;cm",100,0.,30.);


  h_AverageWaveform1       = tfs->make<TH1F>("AverageWaveform1","Average waveform of Michel pulse",
    int(fFullWindowLength)+int(fPrePulseBaselineFit),
    0.,
    double(fFullWindowLength)+double(fPrePulseBaselineFit));
  h_AverageWaveform1 ->GetXaxis()->SetTitle("ns");
  h_AverageWaveform1  ->GetYaxis()->SetTitle("mV");
  
  h_AverageWaveform2       = tfs->make<TH1F>("AverageWaveform2","Average waveform of background pulse",
    int(fFullWindowLength)+int(fPrePulseBaselineFit),
    0.,
    double(fFullWindowLength)+double(fPrePulseBaselineFit));
  h_AverageWaveform2 ->GetXaxis()->SetTitle("ns");
  h_AverageWaveform2  ->GetYaxis()->SetTitle("mV");
  
  h_AverageWaveformMIP       = tfs->make<TH1F>("AverageWaveformMIP","Average waveform of thru-going particles (MIPs)",
    int(fFullWindowLength)+int(fPrePulseBaselineFit),
    0.,
    double(fFullWindowLength)+double(fPrePulseBaselineFit));
  h_AverageWaveformMIP ->GetXaxis()->SetTitle("ns");
  h_AverageWaveformMIP  ->GetYaxis()->SetTitle("mV");
  
  h_AverageWaveformProton       = tfs->make<TH1F>("AverageWaveformProton","Average waveform of protons",
    int(fFullWindowLength)+int(fPrePulseBaselineFit),
    0.,
    double(fFullWindowLength)+double(fPrePulseBaselineFit));
  h_AverageWaveformProton ->GetXaxis()->SetTitle("ns");
  h_AverageWaveformProton  ->GetYaxis()->SetTitle("mV");
}

void MichelWfmReco::beginRun(art::Run & r)
{
  fTrigFiltAlg.loadXMLDatabaseTable( r.run() );
  iEvent = 0; 
}

void MichelWfmReco::beginSubRun(art::SubRun & sr)
{
}

void MichelWfmReco::endJob()
{

  // Make the average waveforms
  
  // Waveform 1 (Michel pulses)
  int N_entries = fOpHitBuilderAlg_ave1.AverageWaveform_count;
  double integral_prompt = 0.;
  double integral_total = 0.;
  if( N_entries > 0 ){
    for( int i = 0; i < (int)fOpHitBuilderAlg_ave1.AverageWaveform.size(); i++) {
      double w = fOpHitBuilderAlg_ave1.AverageWaveform.at(i) / double(N_entries); 
      h_AverageWaveform1->Fill(i,w);
      if( (i>fPrePulseBaselineFit)&&(i<fPrePulseBaselineFit+fPromptWindowLength) ) integral_prompt += w;
      if( (i>fPrePulseBaselineFit) ) integral_total += w; 
    }
  }
  
  std::cout<<"=================================\n";
  std::cout<<"Michel hits (1)\n";
  std::cout<<"Average of "<<N_entries<<" waveforms.\n";
  std::cout<<"   prompt ("<<fPromptWindowLength<<" ns): "<<integral_prompt<<std::endl;
  std::cout<<"   total ("<<fFullWindowLength<<" ns): "<<integral_total<<std::endl;
  std::cout<<"   ratio: "<< integral_prompt / integral_total<<std::endl;
  std::cout<<"================================\n";
  
  
  // Waveform 2 (BG pulses)
  N_entries = fOpHitBuilderAlg_ave2.AverageWaveform_count;
  integral_prompt = 0.;
  integral_total = 0.;
  if( N_entries > 0 ){
    for( int i = 0; i < (int)fOpHitBuilderAlg_ave2.AverageWaveform.size(); i++) {
      double w = fOpHitBuilderAlg_ave2.AverageWaveform.at(i) / double(N_entries); 
      h_AverageWaveform2->Fill(i,w);
      if( (i>fPrePulseBaselineFit)&&(i<fPrePulseBaselineFit+fPromptWindowLength) ) integral_prompt += w;
      if( (i>fPrePulseBaselineFit) ) integral_total += w; 
    }
  }
  std::cout<<"=================================\n";
  std::cout<<"BG hits (2)\n";
  std::cout<<"Average of "<<N_entries<<" waveforms.\n";
  std::cout<<"   prompt ("<<fPromptWindowLength<<" ns): "<<integral_prompt<<std::endl;
  std::cout<<"   total ("<<fFullWindowLength<<" ns): "<<integral_total<<std::endl;
  std::cout<<"   ratio: "<< integral_prompt / integral_total<<std::endl;
  std::cout<<"================================\n";
  
  
  // MIP average waveform
  N_entries = fOpHitBuilderAlg_aveMIP.AverageWaveform_count;
  integral_prompt = 0.;
  integral_total = 0.;
  if( N_entries > 0 ){
    for( int i = 0; i < (int)fOpHitBuilderAlg_aveMIP.AverageWaveform.size(); i++) {
      double w = fOpHitBuilderAlg_aveMIP.AverageWaveform.at(i) / double(N_entries); 
      h_AverageWaveformMIP->Fill(i,w);
      if( (i>fPrePulseBaselineFit)&&(i<fPrePulseBaselineFit+fPromptWindowLength) ) integral_prompt += w;
      if( (i>fPrePulseBaselineFit) ) integral_total += w; 
    }
  }
  std::cout<<"=================================\n";
  std::cout<<"MIPs:\n";
  std::cout<<"Average of "<<N_entries<<" waveforms.\n";
  std::cout<<"   prompt ("<<fPromptWindowLength<<" ns): "<<integral_prompt<<std::endl;
  std::cout<<"   total ("<<fFullWindowLength<<" ns): "<<integral_total<<std::endl;
  std::cout<<"   ratio: "<< integral_prompt / integral_total<<std::endl;
  std::cout<<"================================\n";


  // Proton average waveform
  N_entries = fOpHitBuilderAlg_aveProton.AverageWaveform_count;
  integral_prompt = 0.;
  integral_total = 0.;
  if( N_entries > 0 ){
    for( int i = 0; i < (int)fOpHitBuilderAlg_aveProton.AverageWaveform.size(); i++) {
      double w = fOpHitBuilderAlg_aveProton.AverageWaveform.at(i) / double(N_entries); 
      h_AverageWaveformProton->Fill(i,w);
      if( (i>fPrePulseBaselineFit)&&(i<fPrePulseBaselineFit+fPromptWindowLength) ) integral_prompt += w;
      if( (i>fPrePulseBaselineFit) ) integral_total += w; 
    }
  }
  std::cout<<"=================================\n";
  std::cout<<"Protons:\n";
  std::cout<<"Average of "<<N_entries<<" waveforms.\n";
  std::cout<<"   prompt ("<<fPromptWindowLength<<" ns): "<<integral_prompt<<std::endl;
  std::cout<<"   total ("<<fFullWindowLength<<" ns): "<<integral_total<<std::endl;
  std::cout<<"   ratio: "<< integral_prompt / integral_total<<std::endl;
  std::cout<<"================================\n";

}

void MichelWfmReco::endRun(art::Run & r)
{
}

void MichelWfmReco::endSubRun(art::SubRun & sr)
{
}

void MichelWfmReco::reconfigure(fhicl::ParameterSet const & pset)
{
  // Pass name of TriggerUtility
  fTriggerUtility         = pset.get< std::string >("TriggerUtility","FragmentToDigit");
  bUseTriggerFilter       = pset.get< bool >("UseTriggerFilter","false");
  bUseTrackInformation    = pset.get< bool >("UseTrackInformation","true");
  bVerbose                = pset.get< bool >("Verbosity","false");
  fDAQModule              = pset.get< std::string >("DAQModule","daq");
  fTrackModule            = pset.get< std::string >("TrackModule","pmtrack");
  fTrackCalModule         = pset.get< std::string >("TrackCalModule","calo");
  fParticleIDModule       = pset.get< std::string >("ParticleIDModule","pid");
  fInstanceName           = pset.get< std::string >("InstanceName","");
  fBaselineWindowLength   = pset.get< short >("BaselineWindowLength",1000);
  fPromptWindowLength     = pset.get< short >("PromptWindowLength",100);
  fFullWindowLength       = pset.get< short >("FullWindowLength",7000);
  fPrePulseBaselineFit    = pset.get< short >("PrePulseBaselineFit",300);
  fFiducialMargin_X       = pset.get< double>("FiducialMargin_X",5.);
  fFiducialMargin_Y       = pset.get< double>("FiducialMargin_Y",4.);
  fFiducialMargin_Z       = pset.get< double>("FiducialMargin_Z",5.);
  fTimestampCut           = pset.get< double>("TimestampCut",5.3);
  fGateDelay              = pset.get< short>("GateDelay",300);
  fDtIntegralCut          = pset.get< short>("DtIntegralCut",0);

}

void MichelWfmReco::respondToCloseInputFile(art::FileBlock const & fb)
{
}

void MichelWfmReco::respondToCloseOutputFiles(art::FileBlock const & fb)
{
}

void MichelWfmReco::respondToOpenInputFile(art::FileBlock const & fb)
{
}

void MichelWfmReco::respondToOpenOutputFiles(art::FileBlock const & fb)
{
}

// Function for determining if a point is inside or outside
// predefined fiducial volume
bool MichelWfmReco::IsPointInFiducialVolume(TVector3 p)
{
  double Lx = 47.;
  double Ly = 40.;
  double Lz = 90.;
  if( (fabs(p.Y()       ) > Ly/2. - fFiducialMargin_Y) ||
      (fabs(p.X()-Lx/2. ) > Lx/2. - fFiducialMargin_X) ||
      (fabs(p.Z()-Lz/2. ) > Lz/2. - fFiducialMargin_Z) )
  {
    return false;
  } else {
    return true;
  }
}

DEFINE_ART_MODULE(MichelWfmReco)
