////////////////////////////////////////////////////////////////////////
// Class:       FragmentToDigit
// Module Type: producer
// File:        FragmentToDigit_module.cc
//
// Generated at Mon Dec  1 11:28:13 2014 by Will Flanagan using artmod
// from cetpkgsupport v1_07_01.
////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////
// TODO
//////////////////////////////////////////////////////////////
// [x] Add CAEN V1751 board 0
// [x] Add CAEN V1751 board 1
// [x] Add channels 31 to 63 of CAEN V1740 board 7
// [x] Add CAEN V1740 channels for boards 0-6 and channels 0
//     to 31 of board 7 to TPC RawDigits
// [x] Add WUT
// [x] Add MWPCs
// [x] Put Pawel's OpDetPulse modifications back in (Pawel)
// [x] Add data block matching algorithm
// [ ] Add trigger associations (Brian)
// [ ] Add helpful comments throughout code. This may never be
//     checked off.
//////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"
#include "art/Framework/Services/Optional/TFileService.h"
#include "art/Framework/Services/Optional/TFileDirectory.h"

#include "artdaq-core/Data/Fragment.hh"

#include "LArIATFragments/LariatFragment.h"
#include "LArIATFragments/WUTFragment.h"
#include "LArIATFragments/CAENFragment.h"
#include "LArIATFragments/TDCFragment.h"

#include "SimpleTypesAndConstants/RawTypes.h"
#include "RawData/RawDigit.h"
#include "RawData/AuxDetDigit.h"
#include "RawData/OpDetPulse.h"
#include "SummaryData/RunData.h"
#include "Geometry/Geometry.h"

//#include "TTree.h"
#include "TGraph.h"
#include "TF1.h"

#include <memory>
#include <functional>
#include <vector>
#include <string>
#include <algorithm>

enum {
  V1740_N_CHANNELS = 64,
  V1751_N_CHANNELS = 8,
  WUT_N_TDC_CHANNELS = 16,
  WUT_MAX_HITS = 128,
};

// ugly nested map for matching data blocks
typedef std::map< std::string, std::map< std::string, std::map< unsigned int, std::vector<unsigned int> > > > match_map;

class FragmentToDigit;

class FragmentToDigit : public art::EDProducer {
public:
  explicit FragmentToDigit(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  FragmentToDigit(FragmentToDigit const &) = delete;
  FragmentToDigit(FragmentToDigit &&) = delete;
  FragmentToDigit & operator = (FragmentToDigit const &) = delete;
  FragmentToDigit & operator = (FragmentToDigit &&) = delete;

  // Required functions.
  void produce(art::Event & evt) override;

  // Selected optional functions.
  void beginJob() override;
  void reconfigure(fhicl::ParameterSet const & p) override;
  void beginRun(art::Run &run);
  void matchDataBlocks(LariatFragment * data);

  void coarseMatch(std::string deviceALabel,
		   std::string deviceBLabel,
		   double      range[2],
		   std::map< std::string, std::map<unsigned int, double> > timeStamps,
		   match_map & matchMap);

  void fineMatch(std::string deviceALabel,
		 std::string deviceBLabel,
		 double      range[2],
		 std::pair<double, double> fitParameters,
		 std::map< std::string, std::map<unsigned int, double> > timeStamps,
		 match_map & matchMap);

  void printMatchMap(std::string deviceALabel,
		     std::string deviceBLabel,
		     match_map matchMap);

  double line(std::pair<double, double> parameters, 
	      double                    x);

  std::pair<double, double> fitDrift(std::string deviceALabel,
				     std::string deviceBLabel,
				     std::map< std::string, std::map<unsigned int, double> > timeStamps,
				     match_map   matchMap,
				     std::string graphNamePrefix);

  void matchFragments(uint32_t            & Ntriggers,
		      std::vector<size_t> & fv1751InTrigger,
		      std::vector<size_t> & fv1740InTrigger,
		      std::vector<size_t> & fTDCInTrigger,
		      LariatFragment*       data);

  void makeTPCRawDigits(LariatFragment *data,
			std::unique_ptr< std::vector<raw::RawDigit> > & tpcDigits);
  void makeCaenV1751AuxDetDigits(int i, 
				 LariatFragment*                                    data,
				 std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1751Board0Vec,
				 std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1751Board1Vec,
				 std::unique_ptr<std::vector< raw::OpDetPulse > > & OpDetVec2,
				 std::unique_ptr<std::vector< raw::OpDetPulse > > & OpDetVec1);
  void makeCaenV1740AuxDetDigits(int i,
				 LariatFragment * data,
				 std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1740Board7Vec);
  void makeMWPCTDCAuxDetDigits(int i, LariatFragment * data,
			       std::vector< std::reference_wrapper< std::unique_ptr< std::vector<raw::AuxDetDigit> > > > & mwpcTdcVecs,
			       std::string mwpcTdcLabels[16]);
  void makeWUTDigits(LariatFragment*                                    data,
		     std::unique_ptr< std::vector<raw::AuxDetDigit> > & wutVec);

private:

  art::ServiceHandle<art::TFileService> tfs;

  std::string fRawFragmentLabel;     ///< label for module producing artdaq fragments
  std::string fRawFragmentInstance;  ///< instance label for artdaq fragments        
  std::string fCaenV1740Board0Label;
  std::string fCaenV1740Board1Label;
  std::string fCaenV1740Board2Label;
  std::string fCaenV1740Board3Label;
  std::string fCaenV1740Board4Label;
  std::string fCaenV1740Board5Label;
  std::string fCaenV1740Board6Label;
  std::string fCaenV1740Board7Label;
  std::string fCaenV1751Board0Label;
  std::string fCaenV1751Board1Label;
  std::string fCaenOpLabel1;
  std::string fCaenOpLabel2;
  std::string fWutLabel;
  std::string fMwpcTdc01Label;
  std::string fMwpcTdc02Label;
  std::string fMwpcTdc03Label;
  std::string fMwpcTdc04Label;
  std::string fMwpcTdc05Label;
  std::string fMwpcTdc06Label;
  std::string fMwpcTdc07Label;
  std::string fMwpcTdc08Label;
  std::string fMwpcTdc09Label;
  std::string fMwpcTdc10Label;
  std::string fMwpcTdc11Label;
  std::string fMwpcTdc12Label;
  std::string fMwpcTdc13Label;
  std::string fMwpcTdc14Label;
  std::string fMwpcTdc15Label;
  std::string fMwpcTdc16Label;
  bool fPMTTest;

  // variables from the SpillTrailer fragments
  uint32_t runNumber;
  uint32_t spillNumber;
  uint32_t timeStamp;

  uint32_t fNtriggers;
  std::vector<size_t> fv1751InTrigger;
  std::vector<size_t> fv1740InTrigger;
  std::vector<size_t> fTDCInTrigger;

  // maps for matching fragments
  std::map< std::string, std::map<unsigned int, double> > fFragTimeStamps;
  match_map fPreliminaryMatches;
  match_map fMatches;

  std::vector<std::vector<int>> fOpDetChID;
};

//------------------------------------------------------------------------------
FragmentToDigit::FragmentToDigit(fhicl::ParameterSet const & p)
  : fNtriggers(0)
{
  this->reconfigure(p);

  ///\todo At some point we want to store the POT for each run in the file

  produces< sumdata::RunData, art::InRun >();

  produces< std::vector<raw::RawDigit> >();

  produces< std::vector<raw::AuxDetDigit> >(fCaenV1740Board7Label);
  produces< std::vector<raw::AuxDetDigit> >(fCaenV1751Board0Label);
  produces< std::vector<raw::AuxDetDigit> >(fCaenV1751Board1Label);
  produces< std::vector<raw::AuxDetDigit> >(fWutLabel);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc01Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc02Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc03Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc04Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc05Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc06Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc07Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc08Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc09Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc10Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc11Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc12Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc13Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc14Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc15Label);
  produces< std::vector<raw::AuxDetDigit> >(fMwpcTdc16Label);
  produces< std::vector<raw::OpDetPulse> >(fCaenOpLabel1);
  produces< std::vector<raw::OpDetPulse> >(fCaenOpLabel2);
}

//------------------------------------------------------------------------------
void FragmentToDigit::reconfigure(fhicl::ParameterSet const & p)
{
  fRawFragmentLabel = p.get< std::string >("RawFragmentLabel", "daq");
  fRawFragmentInstance = p.get< std::string >("RawFragmentInstance", "SPILL");
  fCaenV1740Board0Label = p.get< std::string >("CaenV1740Board0Label", "CaenV1740Board0");
  fCaenV1740Board1Label = p.get< std::string >("CaenV1740Board1Label", "CaenV1740Board1");
  fCaenV1740Board2Label = p.get< std::string >("CaenV1740Board2Label", "CaenV1740Board2");
  fCaenV1740Board3Label = p.get< std::string >("CaenV1740Board3Label", "CaenV1740Board3");
  fCaenV1740Board4Label = p.get< std::string >("CaenV1740Board4Label", "CaenV1740Board4");
  fCaenV1740Board5Label = p.get< std::string >("CaenV1740Board5Label", "CaenV1740Board5");
  fCaenV1740Board6Label = p.get< std::string >("CaenV1740Board6Label", "CaenV1740Board6");
  fCaenV1740Board7Label = p.get< std::string >("CaenV1740Board7Label", "CaenV1740Board7");
  fCaenV1751Board0Label = p.get< std::string >("CaenV1751Board0Label", "CaenV1751Board0");
  fCaenV1751Board1Label = p.get< std::string >("CaenV1751Board1Label", "CaenV1751Board1");
  fWutLabel = p.get< std::string >("WutLabel", "Wut");
  fMwpcTdc01Label = p.get< std::string >("MwpcTdc01Label", "MwpcTdc01");
  fMwpcTdc02Label = p.get< std::string >("MwpcTdc02Label", "MwpcTdc02");
  fMwpcTdc03Label = p.get< std::string >("MwpcTdc03Label", "MwpcTdc03");
  fMwpcTdc04Label = p.get< std::string >("MwpcTdc04Label", "MwpcTdc04");
  fMwpcTdc05Label = p.get< std::string >("MwpcTdc05Label", "MwpcTdc05");
  fMwpcTdc06Label = p.get< std::string >("MwpcTdc06Label", "MwpcTdc06");
  fMwpcTdc07Label = p.get< std::string >("MwpcTdc07Label", "MwpcTdc07");
  fMwpcTdc08Label = p.get< std::string >("MwpcTdc08Label", "MwpcTdc08");
  fMwpcTdc09Label = p.get< std::string >("MwpcTdc09Label", "MwpcTdc09");
  fMwpcTdc10Label = p.get< std::string >("MwpcTdc10Label", "MwpcTdc10");
  fMwpcTdc11Label = p.get< std::string >("MwpcTdc11Label", "MwpcTdc11");
  fMwpcTdc12Label = p.get< std::string >("MwpcTdc12Label", "MwpcTdc12");
  fMwpcTdc13Label = p.get< std::string >("MwpcTdc13Label", "MwpcTdc13");
  fMwpcTdc14Label = p.get< std::string >("MwpcTdc14Label", "MwpcTdc14");
  fMwpcTdc15Label = p.get< std::string >("MwpcTdc15Label", "MwpcTdc15");
  fMwpcTdc16Label = p.get< std::string >("MwpcTdc16Label", "MwpcTdc16");
  fOpDetChID = p.get< std::vector<std::vector<int>> >("pmt_channel_ids");
  fCaenOpLabel1 = p.get< std::string >("OpDetBoardLabel1", "Caenv1751Optical1");
  fCaenOpLabel2 = p.get< std::string >("OpDetBoardLabel2", "Caenv1751Optical2");
  fPMTTest = p.get<bool> ("pmt_test");
}

//------------------------------------------------------------------------------
void FragmentToDigit::beginJob()
{
  //art::ServiceHandle<art::TFileService> tfs;

  //fV1751V1740DriftPreliminary = tfs->make<TGraph>();
  //fV1751MwpcDriftPreliminary  = tfs->make<TGraph>();
  //fV1740MwpcDriftPreliminary  = tfs->make<TGraph>();

  return;
}

//____________________________________________________________________________
void FragmentToDigit::beginRun(art::Run& run)
{
  
  // grab the geometry object to see what geometry we are using
  art::ServiceHandle<geo::Geometry> geo;
  
  std::unique_ptr<sumdata::RunData> runcol(new sumdata::RunData(geo->DetectorName()));
  
  run.put(std::move(runcol));
  
  return;
}

//------------------------------------------------------------------------------
void FragmentToDigit::produce(art::Event & evt)
{
for(unsigned int i=0;i<fOpDetChID.size();++i){
	for(unsigned int j=0;j<fOpDetChID[i].size();++j)   mf::LogInfo("FragmentToDigit")<<"channels and boards for opdetpulses : board - channel "<<i<<" - "<<j<<" "<<fOpDetChID[i][j]<<std::endl;
	}
  art::Handle< std::vector<artdaq::Fragment> > fragments;
  evt.getByLabel(fRawFragmentLabel, fRawFragmentInstance, fragments);

  std::unique_ptr< std::vector<raw::RawDigit> > tpcDigitVec(new std::vector<raw::RawDigit>);

  std::unique_ptr< std::vector<raw::AuxDetDigit> > caenV1740Board7Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > caenV1751Board0Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > caenV1751Board1Vec
      (new std::vector<raw::AuxDetDigit>);

  std::unique_ptr< std::vector<raw::AuxDetDigit> > wutVec
      (new std::vector<raw::AuxDetDigit>);

  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc01Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc02Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc03Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc04Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc05Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc06Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc07Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc08Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc09Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc10Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc11Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc12Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc13Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc14Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc15Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr< std::vector<raw::AuxDetDigit> > mwpcTdc16Vec
      (new std::vector<raw::AuxDetDigit>);
  std::unique_ptr<std::vector< raw::OpDetPulse > >  OpDetVec1
      (new std::vector<raw::OpDetPulse>);
  std::unique_ptr<std::vector< raw::OpDetPulse > >  OpDetVec2
      (new std::vector<raw::OpDetPulse>);

  // the following line is way too long
  std::vector< std::reference_wrapper< std::unique_ptr< std::vector<raw::AuxDetDigit> > > > mwpcTdcVecs = {
    mwpcTdc01Vec, mwpcTdc02Vec, mwpcTdc03Vec, mwpcTdc04Vec,
    mwpcTdc05Vec, mwpcTdc06Vec, mwpcTdc07Vec, mwpcTdc08Vec,
    mwpcTdc09Vec, mwpcTdc10Vec, mwpcTdc11Vec, mwpcTdc12Vec,
    mwpcTdc13Vec, mwpcTdc14Vec, mwpcTdc15Vec, mwpcTdc16Vec
  };

  std::string mwpcTdcLabels[16] = {
      fMwpcTdc01Label, fMwpcTdc02Label, fMwpcTdc03Label, fMwpcTdc04Label,
      fMwpcTdc05Label, fMwpcTdc06Label, fMwpcTdc07Label, fMwpcTdc08Label,
      fMwpcTdc09Label, fMwpcTdc10Label, fMwpcTdc11Label, fMwpcTdc12Label,
      fMwpcTdc13Label, fMwpcTdc14Label, fMwpcTdc15Label, fMwpcTdc16Label
      };

  if ( !fragments.isValid() )
      throw cet::exception("FragmentToDigit") << "artdaq::Fragment handle is not valid, bail";
  if ( fragments->size() != 1 )
      throw cet::exception("FragmentToDigit") << "artdaq::Fragment handle contains more than one fragment, bail";

  // get the fragments we are interested in
  const auto& frag((*fragments)[0]);

  const char * bytePtr = reinterpret_cast<const char *> (&*frag.dataBegin());
  LariatFragment * data = new LariatFragment((char *) bytePtr, frag.dataSize() * sizeof(unsigned long long));
  mf::LogInfo("FragmentToDigit")<< "Have data fragment "
				<< frag.dataSize() * sizeof(unsigned long long);
  data->print();
  data->printSpillTrailer();

  LariatFragment::SpillTrailer & spillTrailer = data->spillTrailer;
  runNumber = spillTrailer.runNumber;
  spillNumber = spillTrailer.spillNumber;
  timeStamp = spillTrailer.timeStamp;

  mf::LogInfo("FragmentToDigit") << "evt.run(): " << evt.run()
				 << "; evt.subRun(): " << evt.subRun()
				 << "; evt.event(): " << evt.event()
				 << "; evt.time().timeLow(): " << evt.time().timeLow()
				 << "; evt.time().timeHigh(): " << evt.time().timeHigh()
				 << "\nrunNumber: " << runNumber << "; spillNumber: " << spillNumber
				 << "; timeStamp: " << timeStamp;

  this->makeTPCRawDigits(data, tpcDigitVec);

  //this->matchDataBlocks(data);
  this->matchFragments(fNtriggers, fv1751InTrigger, fv1740InTrigger, fTDCInTrigger, data);

  std::cout<<"Ntriggers is: "<<fNtriggers<<std::endl;

  std::cout<<"The size of v1751InTrigger is: "<<fv1751InTrigger.size()<<std::endl;

  std::cout<<"The size of v1740InTrigger is: "<<fv1740InTrigger.size()<<std::endl;

  std::cout<<"The size of TDCInTrigger is: "<<fTDCInTrigger.size()<<std::endl;

  //produce wvforms for all triggers in selected channels in v1751 if PMTTest is set to true - skip matching for them
  if (fPMTTest){
    for(size_t i=0;i<data->caenFrags.size();++i){
      this->makeCaenV1751AuxDetDigits(i, data, caenV1751Board0Vec, caenV1751Board1Vec, OpDetVec1, OpDetVec2);
    }
  }

  for (size_t i = 0; i < fNtriggers; ++i) {

    mf::LogInfo("FragmentToDigit") << "Trigger " << i << " has a V1751 Fragment with index " << fv1751InTrigger[i] 
				   <<"\n and a V1740 Fragment with index " << fv1740InTrigger[i];
    if (fTDCInTrigger.size()>0) mf::LogInfo("FragmentToDigit") << ", and a TDC Fragment with index " << fTDCInTrigger[i];


    if(fv1751InTrigger[i])
      this->makeCaenV1751AuxDetDigits(fv1751InTrigger[i], data, caenV1751Board0Vec, caenV1751Board1Vec, OpDetVec1, OpDetVec2);

    if(fv1740InTrigger[i])
      this->makeCaenV1740AuxDetDigits(fv1740InTrigger[i], data, caenV1740Board7Vec);

    if(fTDCInTrigger.size() > 0 && fTDCInTrigger[i])
      this->makeMWPCTDCAuxDetDigits(fTDCInTrigger[i], data, mwpcTdcVecs, mwpcTdcLabels);

  }

  this->makeWUTDigits(data, wutVec);

  evt.put(std::move(tpcDigitVec));
  evt.put(std::move(caenV1740Board7Vec), fCaenV1740Board7Label);
  evt.put(std::move(caenV1751Board0Vec), fCaenV1751Board0Label);
  evt.put(std::move(caenV1751Board1Vec), fCaenV1751Board1Label);
  evt.put(std::move(OpDetVec1), fCaenOpLabel1);
  evt.put(std::move(OpDetVec2), fCaenOpLabel2);
  evt.put(std::move(wutVec), fWutLabel);

  for (size_t i = 0; i < TDCFragment::MAX_TDCS; ++i) {
    evt.put(std::move(mwpcTdcVecs[i].get()), mwpcTdcLabels[i]);
  }

  fv1751InTrigger.clear();
  fv1740InTrigger.clear();
  fTDCInTrigger.clear();

  return;  
}

//-----------------------------------------------------------------------------------
void FragmentToDigit::matchDataBlocks(LariatFragment * data) 
{

  //std::map< std::string, std::map<unsigned int, double> > fFragTimeStamps;

  //////////////////////////////////////////////////////////////////////
  // Some notes
  //////////////////////////////////////////////////////////////////////
  //
  // There are multiple CAEN fragments and only one TDC fragment for
  // each spill. Each TDC fragment holds multiple TDC events.
  //
  // Since there are multiple CAEN fragments and only one TDC fragment
  // per spill, I will use the term "data block" to refer to a single
  // CAEN fragment or a single TDC event.
  //
  // fFragTimeStamps will store the data block time stamps from all
  // devices (except the WUT) to help with the matching.
  //
  // Here is some pseudocode on how to access the time stamps:
  //
  // for deviceLabel in devices:
  //     for dataBlockIndex in dataBlocks:
  //         dataBlockTimeStamp = fFragTimeStamps[deviceLabel][dataBlockIndex];
  //
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //@\ BEGIN: loop through the data blocks to get their time stamps
  //          into fFragTimeStamps
  //////////////////////////////////////////////////////////////////////

  size_t numberCaenDataBlocks[10] = {};
  size_t numberMwpcDataBlocks = 0;

  std::string caenLabels[10] = {
    fCaenV1740Board0Label,
    fCaenV1740Board1Label,
    fCaenV1740Board2Label,
    fCaenV1740Board3Label,
    fCaenV1740Board4Label,
    fCaenV1740Board5Label,
    fCaenV1740Board6Label,
    fCaenV1740Board7Label,
    fCaenV1751Board0Label,
    fCaenV1751Board1Label
  };

  std::string mwpcTdcLabels[TDCFragment::MAX_TDCS] = {
      fMwpcTdc01Label,
      fMwpcTdc02Label,
      fMwpcTdc03Label,
      fMwpcTdc04Label,
      fMwpcTdc05Label,
      fMwpcTdc06Label,
      fMwpcTdc07Label,
      fMwpcTdc08Label,
      fMwpcTdc09Label,
      fMwpcTdc10Label,
      fMwpcTdc11Label,
      fMwpcTdc12Label,
      fMwpcTdc13Label,
      fMwpcTdc14Label,
      fMwpcTdc15Label,
      fMwpcTdc16Label
  };

  const size_t numberCaenFrags = data->caenFrags.size();
  mf::LogInfo("FragmentToDigit") << "Found " << numberCaenFrags << " CAEN fragments";

  if (numberCaenFrags > 0) 
    mf::LogInfo("FragmentToDigit") << "Looking at CAEN fragments...";

  for (size_t i = 0; i < numberCaenFrags; ++i) {
    CAENFragment & caenFrag = data->caenFrags[i];
    unsigned int boardId = static_cast <unsigned int> (caenFrag.header.boardId);
    std::string label = caenLabels[boardId];
    unsigned int index = numberCaenDataBlocks[boardId];
    // each CAEN Trigger Time Tag count is 8 ns
    double timeStamp = caenFrag.header.triggerTimeTag * 0.008;  // convert to microseconds
    fFragTimeStamps[label][index] = timeStamp;
    numberCaenDataBlocks[boardId] += 1;
  }

  const int numberTdcFrags = data->tdcFrags.size();
  mf::LogInfo("FragmentToDigit") << "Found " << numberTdcFrags << " TDC fragments";

  if (numberTdcFrags > 0) 
    mf::LogInfo("FragmentToDigit") << "Looking at TDC fragments...";
  

  for (int i = 0; i < numberTdcFrags; ++i) {

    TDCFragment & tdcFrag = data->tdcFrags[i];

    std::vector< std::vector<TDCFragment::TdcEventData> > &tdcEvents = tdcFrag.tdcEvents;

    //LOG_DEBUG("FragmentToDigit")
    //    << "tdcEvents.size(): " << tdcEvents.size();
    //tdcFrag.print();

    numberMwpcDataBlocks = tdcEvents.size();

    for (size_t j = 0; j < tdcEvents.size(); ++j) {

      if (tdcFrag.controllerHeader.nTDCs != tdcEvents[j].size()) {
        mf::LogError("FragmentToDigit") << "*** Fatal nTDCs mismatch: " << tdcEvents[j].size()
				<< " != " << tdcFrag.controllerHeader.nTDCs<< " "<< j;
	continue;
      }

      LOG_DEBUG("FragmentToDigit") << "TDC event: " << j;

      for (size_t tdc_index = 0; tdc_index < TDCFragment::MAX_TDCS; ++tdc_index) {
        TDCFragment::TdcEventData tdcEventData = tdcEvents[j].at(tdc_index);

        uint16_t controllerTimeStamp = tdcEventData.tdcEventHeader.controllerTimeStamp;
        uint32_t tdcTimeStamp = tdcEventData.tdcEventHeader.tdcTimeStamp;
        // each TDC Time Stamp count is 1/106.208 microseconds
        double timeStamp = tdcEventData.tdcEventHeader.tdcTimeStamp / 106.208;  // convert to microseconds

        std::string label = mwpcTdcLabels[tdc_index];

        LOG_DEBUG("FragmentToDigit") << "  TDC index: " << tdc_index;
        LOG_DEBUG("FragmentToDigit") << "  Label: " << label;
        LOG_DEBUG("FragmentToDigit") << "  TDC time stamp: " << tdcTimeStamp;
        LOG_DEBUG("FragmentToDigit") << "  Controller time stamp: " << controllerTimeStamp;

        fFragTimeStamps[label][j] = timeStamp;

      }
    }
  }

  // let's forget the WUT for now
  //const int numberWutFrags = data->wutFrags.size();
  //mf::LogInfo("FragmentToDigit")
  //    << "Found " << numberWutFrags << " WUT fragments";

  //////////////////////////////////////////////////////////////////////
  //@\ END: loop through the data blocks to get their time stamps
  //        into fFragTimeStamps
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //@\ BEGIN: loop through fFragTimeStamps to check that they are there
  //////////////////////////////////////////////////////////////////////

  for (size_t i = 0; i < 10; ++i) {
    std::string label = caenLabels[i];
    unsigned int indices = numberCaenDataBlocks[i];
    LOG_DEBUG("FragmentToDigit") << "Board ID: " << i << ", number of data blocks: " << numberCaenDataBlocks[i];
    LOG_DEBUG("FragmentToDigit") << "Label: " << label;
    for (size_t j = 0; j < indices; ++j) {
      LOG_DEBUG("FragmentToDigit") << "  Index: " << j;
      LOG_DEBUG("FragmentToDigit") << "  Time stamp: " << fFragTimeStamps[label][j];
    }
  }

  for (size_t i = 0; i < TDCFragment::MAX_TDCS; ++i) {
    std::string label = mwpcTdcLabels[i];
    LOG_DEBUG("FragmentToDigit") << "TDC index: " << i << ", number of data blocks: " << numberMwpcDataBlocks;
    LOG_DEBUG("FragmentToDigit") << "Label: " << label;
    for (size_t j = 0; j < numberMwpcDataBlocks; ++j) {
      LOG_DEBUG("FragmentToDigit") << "  Index: " << j;
      LOG_DEBUG("FragmentToDigit") << "  Time stamp: " << fFragTimeStamps[label][j];
    }
  }

  //////////////////////////////////////////////////////////////////////
  //@\ END: loop through fFragTimeStamps to check that they are there
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //@\ BEGIN: intra V1740/V1751 matching
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  // NOTE: The master clocks of the V1740s is boardId 0; the master
  //       clock of the V1751s is boardId 8.
  //////////////////////////////////////////////////////////////////////

  // the difference in time stamps should be in between this range for a match; microseconds
  double v1740IntraRange[2] = { -0.016, 0.016 };
  double v1751IntraRange[2] = { -0.016, 0.016 };

  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board1Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board2Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board3Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board4Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board5Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board6Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1740Board0Label, fCaenV1740Board7Label, v1740IntraRange, fFragTimeStamps, fMatches);
  coarseMatch(fCaenV1751Board0Label, fCaenV1751Board1Label, v1751IntraRange, fFragTimeStamps, fMatches);

  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board1Label, fMatches);
  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board2Label, fMatches);
  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board3Label, fMatches);
  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board4Label, fMatches);
  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board5Label, fMatches);
  //printMatchMap(fCaenV1740Board0Label, fCaenV1740Board6Label, fMatches);
  //printMatchMap(fCaenV1751Board0Label, fCaenV1751Board1Label, fMatches);

  //////////////////////////////////////////////////////////////////////
  //@\ END: intra V1740/V1751 matching
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //@\ BEGIN: coarse matching
  //////////////////////////////////////////////////////////////////////

  // the difference in time stamps should be in between this range for a match; microseconds
  double v1751v1740InterRange[2] = { 2,   5 };
  double v1751MwpcInterRange[2]  = { 0, 160 };
  double v1740MwpcInterRange[2]  = { 0, 160 };

  std::map< std::string, std::map< std::string, std::pair<double, double> > > fitParameters;

  coarseMatch(fCaenV1751Board0Label, fCaenV1740Board0Label, v1751v1740InterRange, fFragTimeStamps, fPreliminaryMatches);
  coarseMatch(fCaenV1751Board0Label, fMwpcTdc01Label, v1751MwpcInterRange, fFragTimeStamps, fPreliminaryMatches);
  coarseMatch(fCaenV1740Board0Label, fMwpcTdc01Label, v1740MwpcInterRange, fFragTimeStamps, fPreliminaryMatches);

  //printMatchMap(fCaenV1751Board0Label, fCaenV1740Board0Label, fPreliminaryMatches);
  //printMatchMap(fCaenV1751Board0Label, fMwpcTdc01Label, fPreliminaryMatches);
  //printMatchMap(fCaenV1740Board0Label, fMwpcTdc01Label, fPreliminaryMatches);

  fitParameters[fCaenV1751Board0Label][fCaenV1740Board0Label] = fitDrift(fCaenV1751Board0Label, fCaenV1740Board0Label, fFragTimeStamps, fPreliminaryMatches, "coarse_match");
  fitParameters[fCaenV1751Board0Label][fMwpcTdc01Label] = fitDrift(fCaenV1751Board0Label, fMwpcTdc01Label, fFragTimeStamps, fPreliminaryMatches, "coarse_match");
  fitParameters[fCaenV1740Board0Label][fMwpcTdc01Label] = fitDrift(fCaenV1740Board0Label, fMwpcTdc01Label, fFragTimeStamps, fPreliminaryMatches, "coarse_match");

  //////////////////////////////////////////////////////////////////////
  //@\ END: coarse matching
  //////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //@\ BEGIN: fine matching
  //////////////////////////////////////////////////////////////////////

  double v1751v1740InterEps[2] = { 1, 1 };
  double v1751MwpcInterEps[2]  = { 1, 1 };
  double v1740MwpcInterEps[2]  = { 1, 1 };

  fineMatch(fCaenV1751Board0Label, fCaenV1740Board0Label, v1751v1740InterEps, fitParameters[fCaenV1751Board0Label][fCaenV1740Board0Label], fFragTimeStamps, fMatches);
  fineMatch(fCaenV1751Board0Label, fMwpcTdc01Label, v1751MwpcInterEps, fitParameters[fCaenV1751Board0Label][fMwpcTdc01Label], fFragTimeStamps, fMatches);
  fineMatch(fCaenV1740Board0Label, fMwpcTdc01Label, v1740MwpcInterEps, fitParameters[fCaenV1740Board0Label][fMwpcTdc01Label], fFragTimeStamps, fMatches);

  fitParameters[fCaenV1751Board0Label][fCaenV1740Board0Label] = fitDrift(fCaenV1751Board0Label, fCaenV1740Board0Label, fFragTimeStamps, fMatches, "fine_match");
  fitParameters[fCaenV1751Board0Label][fMwpcTdc01Label] = fitDrift(fCaenV1751Board0Label, fMwpcTdc01Label, fFragTimeStamps, fMatches, "fine_match");
  fitParameters[fCaenV1740Board0Label][fMwpcTdc01Label] = fitDrift(fCaenV1740Board0Label, fMwpcTdc01Label, fFragTimeStamps, fMatches, "fine_match");

  //////////////////////////////////////////////////////////////////////
  //@\ END: fine matching
  //////////////////////////////////////////////////////////////////////

  return;
}

//-----------------------------------------------------------------------------------
void FragmentToDigit::coarseMatch(std::string deviceALabel,
				  std::string deviceBLabel,
				  double range[2],
				  std::map< std::string, std::map<unsigned int, double> > timeStamps,
				  match_map & matchMap) 
{
  
  std::map< unsigned int, std::vector<unsigned int> > matchAB;

  size_t numberADataBlocks = timeStamps[deviceALabel].size();
  size_t numberBDataBlocks = timeStamps[deviceBLabel].size();

  for (size_t a = 0; a < numberADataBlocks; ++a) {
    double timeStampA = timeStamps[deviceALabel][a];
    for (size_t b = 0; b < numberBDataBlocks; ++b) {
      double timeStampB = timeStamps[deviceBLabel][b];
      double difference = timeStampA - timeStampB;
      if (range[0] <= difference and difference <= range[1]) {
        matchAB[a].push_back(b);
      }
    }
  }

  matchMap[deviceALabel][deviceBLabel] = matchAB;

  return;
}

//-----------------------------------------------------------------------------------
void FragmentToDigit::fineMatch(std::string deviceALabel,
				std::string deviceBLabel,
				double eps[2],
				std::pair<double, double> fitParameters,
				std::map< std::string, std::map<unsigned int, double> > timeStamps,
				match_map & matchMap) 
{

  std::map< unsigned int, std::vector<unsigned int> > matchAB;

  size_t numberADataBlocks = timeStamps[deviceALabel].size();
  size_t numberBDataBlocks = timeStamps[deviceBLabel].size();

  for (size_t a = 0; a < numberADataBlocks; ++a) {
    double timeStampA = timeStamps[deviceALabel][a];
    for (size_t b = 0; b < numberBDataBlocks; ++b) {
      double timeStampB = timeStamps[deviceBLabel][b];
      double difference = timeStampA - timeStampB;
      double y = line(fitParameters, timeStampA);
      double yLow = y - eps[0];
      double yHigh = y + eps[1];
      if (yLow <= difference and difference <= yHigh) {
        matchAB[a].push_back(b);
      }
    }
  }

  matchMap[deviceALabel][deviceBLabel] = matchAB;

  return;
}

//-----------------------------------------------------------------------------------
double FragmentToDigit::line(std::pair<double, double> parameters, double x) 
{
  double intercept = parameters.first;
  double slope = parameters.second;
  return intercept + slope * x;
}

//-----------------------------------------------------------------------------------
std::pair<double, double> FragmentToDigit::fitDrift(std::string deviceALabel,
						    std::string deviceBLabel,
						    std::map< std::string, std::map<unsigned int, double> > timeStamps,
						    match_map matchMap,
						    std::string graphNamePrefix) 
{

  std::vector<double> x;
  std::vector<double> y;

  std::vector<double> x_;
  std::vector<double> y_;

  std::map< unsigned int, std::vector<unsigned int> > matchAB = matchMap[deviceALabel][deviceBLabel];

  LOG_DEBUG("FragmentToDigit") << "Matches between " << deviceALabel << " and " << deviceBLabel;
  LOG_DEBUG("FragmentToDigit") << "  Matching index pair format: " << "(" << deviceALabel << ", " << deviceBLabel << ")";

  for (auto const & itA : matchAB) {
    LOG_DEBUG("FragmentToDigit") << "  Index: " << itA.first << "; number of matches: " << itA.second.size();
    for (auto const & itB : itA.second) {
      double timeStampA = timeStamps[deviceALabel][itA.first];
      double timeStampB = timeStamps[deviceBLabel][itB];
      double difference = timeStampA - timeStampB;
      double reference = timeStampA;
      LOG_DEBUG("FragmentToDigit") << "    (" << itA.first << ", " << itB << ")"
				   << "; difference: " << difference << " usec"
				   << "; reference: " << reference << " usec";
      if (itA.second.size() == 1) {
        x.push_back(reference);
        y.push_back(difference);
      }
      else {
        x_.push_back(reference);
        y_.push_back(difference);
      }
    }
  }

  std::string graphName = graphNamePrefix + "_drift_" + deviceALabel + "_" + deviceBLabel;
  std::string graphTitles = ("; Time since beginning of spill (using " + deviceALabel 
			     + " clock) [#mus]; #Delta t between "     + deviceALabel 
			     + " and " + deviceBLabel + " [#mus]");

  TGraph * graph = tfs->make<TGraph>(x.size(), &x[0], &y[0]);
  TF1 * f = tfs->make<TF1>("f", "pol1", 0, 30e6);
  graph->Fit("f", "Q");
  graph->SetMarkerStyle(20);
  graph->SetTitle(graphTitles.c_str());
  graph->Write(graphName.c_str());
  LOG_DEBUG("FragmentToDigit") << "Fit parameters: intercept, "
			       << f->GetParameter(0) << " usec; slope, "
			       << f->GetParameter(1) << " usec/usec";

  return std::make_pair<double, double>(f->GetParameter(0), f->GetParameter(1));
}

//------------------------------------------------------------------------------
void FragmentToDigit::printMatchMap(std::string deviceALabel,
				    std::string deviceBLabel,
				    match_map matchMap) 
{

  std::map< unsigned int, std::vector<unsigned int> > matchAB = matchMap[deviceALabel][deviceBLabel];

  LOG_DEBUG("FragmentToDigit") << "Matches between " << deviceALabel << " and " << deviceBLabel;
  LOG_DEBUG("FragmentToDigit") << "  Matching index pair format: " << "(" << deviceALabel << ", " << deviceBLabel << ")";

  for (auto const & itA : matchAB) {
    for (auto const & itB : itA.second) {
      mf::LogVerbatim("FragmentToDigit") << "  (" << itA.first << ", " << itB << ")";
    }
  }

  return;
}

//----------------------------------------------------------------------------------------------
// Matching v1751, v1740, and TDC fragments
// CAEN triggerTimeTag must be multiplied by 0.008 to get microseconds since the start of spill
// TDC tdcTimeStamp must be divided by 106.208 to get microseconds since the start of spill
// I am currently calling triggers within 200 microseconds a match
void FragmentToDigit::matchFragments(uint32_t & fNtriggers,
                                     std::vector<size_t> & fv1751InTrigger,
                                     std::vector<size_t> & fv1740InTrigger,
                                     std::vector<size_t> & fTDCInTrigger,
                                     LariatFragment * data)
{

  size_t v1751FragNumber = 1;
  size_t numberOf1740Matches = 0;
  size_t numberOfTDCMatches = 0;

  mf::LogInfo("FragmentToDigit") << "Lets do some fragment timestamp matching so that we can group triggers...";

  const size_t numberCaenFrags = data->caenFrags.size();
  mf::LogInfo("FragmentToDigit") << "Found " << numberCaenFrags << " CAEN fragments";

  const int numberTdcFrags = data->tdcFrags.size();
  mf::LogInfo("FragmentToDigit") << "Found " << numberTdcFrags << " TDC fragments";

  if (numberCaenFrags > 0)
    mf::LogInfo("FragmentToDigit") << "Begin trigger matching against V1751 CAEN fragments...";

  for (size_t i = 0; i < numberCaenFrags; ++i) {

    numberOf1740Matches = 0;
    numberOfTDCMatches = 0;
    CAENFragment & caenFrag = data->caenFrags[i];

    if (caenFrag.header.boardId == 9) {

      fv1751InTrigger.push_back(i);
      mf::LogInfo("FragmentToDigit") << "v1751 fragment number "<< v1751FragNumber 
				     << " at t=" << caenFrag.header.triggerTimeTag*0.008 << "us";

      for (size_t k = 0; k < numberCaenFrags; ++k) {

        CAENFragment & secondCaenFrag = data->caenFrags[k];

        if (secondCaenFrag.header.boardId == 7 && std::abs(secondCaenFrag.header.triggerTimeTag*0.008 - caenFrag.header.triggerTimeTag*0.008)<200) {

          ++numberOf1740Matches;
          if(numberOf1740Matches == 1) fv1740InTrigger.push_back(k);

        }

      }

      if(numberOf1740Matches == 0) fv1740InTrigger.push_back(0);
      mf::LogInfo("FragmentToDigit") << " has " << numberOf1740Matches << " matching v1740 fragments ";


      // There is always one TDC fragment, so I am no longer looping over TDC fragments.
      // Different TDC triggers can be found by looping over TDC events

      //if( data->tdcFrags.size() < 1) continue;
      if( data->tdcFrags.size() >0){
	TDCFragment & tdcFrag = data->tdcFrags[0];
	
	for (size_t l = 0; l < tdcFrag.tdcEvents.size(); ++l) {
	  
	  if (std::abs(tdcFrag.tdcEvents[l].at(0).tdcEventHeader.tdcTimeStamp/106.208 - caenFrag.header.triggerTimeTag*0.008)<200) {
	    
	    ++numberOfTDCMatches;
	    if(numberOfTDCMatches == 1) fTDCInTrigger.push_back(l);	    
	  }
	}//end loop over tdcEvents

	if(numberOfTDCMatches == 0) fTDCInTrigger.push_back(0);
	mf::LogInfo("FragmentToDigit") << " and " << numberOfTDCMatches << " matching TDC fragments ";
      }
      ++v1751FragNumber;
      mf::LogInfo("FragmentToDigit") << "At i=" << i << "  v1751FragNumber:" << v1751FragNumber;
    }

  }

  fNtriggers=v1751FragNumber-1;

}

//------------------------------------------------------------------------------
void FragmentToDigit::makeTPCRawDigits(LariatFragment *data,
				       std::unique_ptr< std::vector<raw::RawDigit> > & tpcDigits)
{

  std::vector<CAENFragment> const& caenFrags = data->caenFrags;

  raw::ChannelID_t tpcChan = 0;
  size_t maxChan = 64;

  for(auto const& frag : caenFrags){
    
    // the TPC mapping has the readout going to boards 0-7 of
    // the CAEN 1751, channels 0-63 of the boards 0-6, channels 0-31 of board 7
    if(frag.header.boardId > 7) continue;
    else{
      if(frag.header.boardId < 7) maxChan = 64;
      else maxChan = 32;
      for(size_t chan = 0; chan < maxChan; ++chan){ 
	if(chan > frag.waveForms.size() )
	  throw cet::exception("FragmentToDigit") << "attempting to access channel "
						  << chan << " from 1751 fragment with only "
						  << frag.waveForms.size() << " channels";

	tpcChan = (frag.header.boardId * 64) + chan;
	std::vector<short> const adc(frag.waveForms[chan].data.begin(), frag.waveForms[chan].data.end());
	raw::RawDigit rd(tpcChan, adc.size(), adc);
	rd.SetPedestal(2048);
	tpcDigits->push_back(rd);
      } // end loop to fill channels from this board
    }// end if it is a TPC board      
  }// end loop over caen fragments

  return;
  
}

//------------------------------------------------------------------------------
void FragmentToDigit::makeCaenV1751AuxDetDigits(int i, LariatFragment * data,
                                                std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1751Board0Vec,
                                                std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1751Board1Vec,
						std::unique_ptr<std::vector< raw::OpDetPulse > > & OpDetVec1,
						std::unique_ptr<std::vector< raw::OpDetPulse > > & OpDetVec2)
{

  CAENFragment & caenFrag = data->caenFrags[i];

  uint32_t boardId = caenFrag.header.boardId;
  uint32_t triggerTimeTag = caenFrag.header.triggerTimeTag;
  for (size_t j = 0; j < V1751_N_CHANNELS; ++j) {
    std::vector<short> caenFragWaveForm(caenFrag.waveForms[j].data.begin(), caenFrag.waveForms[j].data.end());
    caenV1751Board0Vec->push_back(raw::AuxDetDigit(static_cast <unsigned short> (j),
						   caenFragWaveForm,
						   fCaenV1751Board0Label,
						   static_cast <unsigned long long> (triggerTimeTag)
						   )
				  );

    if(fOpDetChID[boardId].size() != 0){
      if(fOpDetChID[boardId].size() > j){
	mf::LogInfo("FragmentToDigit") << "Writing opdetpulses index i=" << i 
				       << " in makeCaenV1751Frags boardID : " << boardId 
				       << " channel " << j 
				       << " size of wvform data " << caenFrag.waveForms[j].data.size()
				       << " fOpDetChID[boardId] size() " << fOpDetChID[boardId].size() 
				       << " boardId " << boardId;
	if(fOpDetChID[boardId][j] == int(j)){
	  if(boardId == 8)
	    OpDetVec1->push_back(raw::OpDetPulse(static_cast <unsigned short> (j),
						 caenFragWaveForm,
						 0,
						 static_cast <unsigned int> (triggerTimeTag)
						 )
				 );
	  else if (boardId == 9) 
	    OpDetVec2->push_back(raw::OpDetPulse(static_cast <unsigned short> (j),
						 caenFragWaveForm,
						 0,
						 static_cast <unsigned int> (triggerTimeTag)
						 )
				 );
	}//end if the board is the right one
      }//end if the board is the right one        
    }// end if this op channel is valid
  }// end loop over 1751 channels

  return;
}

//------------------------------------------------------------------------------
void FragmentToDigit::makeCaenV1740AuxDetDigits(int i, LariatFragment * data,
						std::unique_ptr< std::vector<raw::AuxDetDigit> > & caenV1740Board7Vec)
{

  CAENFragment & caenFrag = data->caenFrags[i];

  uint32_t boardId = caenFrag.header.boardId;
  uint32_t triggerTimeTag = caenFrag.header.triggerTimeTag;

  if (boardId == 7) {
    for (size_t j = 31; j < V1740_N_CHANNELS; ++j) {
      std::vector<short> caenFragWaveForm(caenFrag.waveForms[j].data.begin(),
					  caenFrag.waveForms[j].data.end());
      caenV1740Board7Vec->push_back(raw::AuxDetDigit(static_cast <unsigned short> (j),
						     caenFragWaveForm,
						     fCaenV1740Board7Label,
						     static_cast <unsigned long long> (triggerTimeTag)
						     )
				    );
    }

  }

}

//------------------------------------------------------------------------------
void FragmentToDigit::makeMWPCTDCAuxDetDigits(int i, LariatFragment * data,
					      std::vector< std::reference_wrapper< std::unique_ptr< std::vector<raw::AuxDetDigit> > > > & mwpcTdcVecs,
					      std::string mwpcTdcLabels[16])
{
  TDCFragment & tdcFrag = data->tdcFrags[0];
  
  std::vector< std::vector<TDCFragment::TdcEventData> > &tdcEvents = tdcFrag.tdcEvents;

  // if the size of the number of TDCs from the fragment does not match the 
  // number of the tdcEvents, then return without doing anything
  if (tdcFrag.controllerHeader.nTDCs != tdcEvents[i].size()) {
    mf::LogError("FragmentToDigit") << "*** Fatal nTDCs mismatch: " 
				    << tdcEvents[i].size()
				    << " != " << tdcFrag.controllerHeader.nTDCs
				    <<" return to calling function";
    return;
  }

  for (size_t tdc_index = 0; tdc_index < TDCFragment::MAX_TDCS; ++tdc_index) {
    TDCFragment::TdcEventData tdcEventData = tdcEvents[i].at(tdc_index);
    
    std::vector< std::vector<short> > hitsInChannel;
    
    hitsInChannel.resize(TDCFragment::N_CHANNELS);
    for (size_t channel = 0; channel < TDCFragment::N_CHANNELS; ++channel) {
      hitsInChannel[channel].reserve(TDCFragment::MAX_HITS);
    }
    
    uint32_t tdcTimeStamp = tdcEventData.tdcEventHeader.tdcTimeStamp;
    
    for (size_t hit_index = 0; hit_index < tdcEventData.tdcHits.size(); ++hit_index) {
      TDCFragment::TdcHit & hit = tdcEventData.tdcHits[hit_index];
      hitsInChannel[size_t (hit.channel)].push_back(short (hit.timeBin));
    }
    
    for (size_t channel = 0; channel < TDCFragment::N_CHANNELS; ++channel) {
      
      mwpcTdcVecs[tdc_index].get()->push_back(raw::AuxDetDigit(static_cast <unsigned short> (channel),
							       hitsInChannel[channel],
							       mwpcTdcLabels[tdc_index],
							       static_cast <unsigned long long> (tdcTimeStamp)
							       )
					      );

    }

  }

  return;
}

//------------------------------------------------------------------------------
void FragmentToDigit::makeWUTDigits(LariatFragment * data,
                                    std::unique_ptr< std::vector<raw::AuxDetDigit> > & wutVec)
{

  const int numberWutFrags = data->wutFrags.size();
  mf::LogInfo("FragmentToDigit") << "Found " << numberWutFrags << " WUT fragments";

  if (numberWutFrags > 0)
    mf::LogInfo("FragmentToDigit") << "Looking at WUT fragments...";

  for (int i = 0; i < numberWutFrags; ++i) {
    WUTFragment & wutFrag = data->wutFrags[i];
    uint32_t numberHits = wutFrag.header.nHits;
    std::vector<WUTFragment::WutHit> & hits = wutFrag.hits;

    std::vector< std::vector<short> > hitsInChannel;

    hitsInChannel.resize(WUT_N_TDC_CHANNELS);
    for (size_t channel = 0; channel < WUT_N_TDC_CHANNELS; ++channel)
      hitsInChannel[channel].reserve(WUT_MAX_HITS);
    
    uint32_t timeHeader = wutFrag.header.timeHeader;

    for (size_t j = 0; j < numberHits; ++j) {
      WUTFragment::WutHit & hit = hits[j];
      hitsInChannel[size_t (hit.channel)].push_back(short (hit.timeBin));
    }

    for (size_t channel = 0; channel < WUT_N_TDC_CHANNELS; ++channel) {

      wutVec->push_back(raw::AuxDetDigit(static_cast <unsigned short> (channel),
					 hitsInChannel[channel],
					 fWutLabel,
					 static_cast <unsigned long long> (timeHeader)
					 )
			);
      
    }
  }// end loop over WUT fragments

  return;
}

DEFINE_ART_MODULE(FragmentToDigit)
